
ALTER TABLE public."MonitoringPost" ADD "Address" text NULL;
--
-- Name: Cameras; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Cameras" (
    "Id" integer NOT NULL,
    "Name" character varying(200) NOT NULL,
    "WebUrl" text,
    "RtspUrl" text NOT NULL,
    "PollingInterval" integer CONSTRAINT "Cameras_Port_not_null" NOT NULL,
    "Username" text,
    "Password" text,
    "IsPtzSupported" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ApiRequest" text,
    "FdaId" text,
    "InstallationLocation" text,
    "MonitoringPostId" integer,
    "Picket" text,
    "SerialNumber" text
);



ALTER TABLE public."Cameras" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Cameras_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


CREATE TABLE public."Snapshots" (
    "Id" integer NOT NULL,
    "CameraId" integer NOT NULL,
    "FilePath" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);



ALTER TABLE public."Snapshots" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Snapshots_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Cameras PK_Cameras; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Cameras"
    ADD CONSTRAINT "PK_Cameras" PRIMARY KEY ("Id");


--

ALTER TABLE ONLY public."Snapshots"
    ADD CONSTRAINT "PK_Snapshots" PRIMARY KEY ("Id");



CREATE INDEX "IX_Cameras_MonitoringPostId" ON public."Cameras" USING btree ("MonitoringPostId");



CREATE INDEX "IX_Snapshots_CameraId" ON public."Snapshots" USING btree ("CameraId");



ALTER TABLE ONLY public."Cameras"
    ADD CONSTRAINT "FK_Cameras_MonitoringPost_MonitoringPostId" FOREIGN KEY ("MonitoringPostId") REFERENCES public."MonitoringPost"("Id") ;



ALTER TABLE ONLY public."Snapshots"
    ADD CONSTRAINT "FK_Snapshots_Cameras_CameraId" FOREIGN KEY ("CameraId") REFERENCES public."Cameras"("Id") ;



