
-- Dumped from database version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: AuditLogs; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."AuditLogs" (
    "Id" integer NOT NULL,
    "Type" integer NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "UserId" integer,
    "UserName" character varying(100),
    "Action" character varying(200),
    "Details" character varying(1000),
    "TargetId" integer,
    "HttpMethod" character varying(10),
    "Url" character varying(500),
    "IpAddress" character varying(50),
    "UserAgent" character varying(500),
    "IsSuccess" boolean,
    "ExecutionTimeMs" bigint,
    "EntityType" character varying(200),
    "EntityId" integer,
    "ChangeType" character varying(50),
    "OriginalValues" jsonb,
    "NewValues" jsonb,
    "ChangedProperties" jsonb
);


ALTER TABLE public."AuditLogs" OWNER TO postgres;

--
-- Name: AuditLogs_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AuditLogs" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AuditLogs_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Cameras; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Cameras" (
    "Id" integer NOT NULL,
    "Name" character varying(200) NOT NULL,
    "WebUrl" text,
    "RtspUrl" text NOT NULL,
    "PollingInterval" integer NOT NULL,
    "Username" text,
    "Password" text,
    "IsPtzSupported" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ApiRequest" text,
    "FdaId" text,
    "InstallationLocation" text,
    "MonitoringPostId" integer,
    "Picket" text,
    "SerialNumber" text
);


ALTER TABLE public."Cameras" OWNER TO postgres;

--
-- Name: Cameras_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Cameras" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Cameras_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: DOVData; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."DOVData" (
    "Id" integer NOT NULL,
    "SensorId" integer NOT NULL,
    "ReceivedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "DataTimestamp" timestamp with time zone NOT NULL,
    "VisibleRange" numeric(10,2),
    "BrightFlag" integer
);


ALTER TABLE public."DOVData" OWNER TO postgres;

--
-- Name: DOVData_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."DOVData_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."DOVData_Id_seq" OWNER TO postgres;

--
-- Name: DOVData_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."DOVData_Id_seq" OWNED BY public."DOVData"."Id";


--
-- Name: DSPDData; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."DSPDData" (
    "Id" integer NOT NULL,
    "SensorId" integer NOT NULL,
    "ReceivedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "DataTimestamp" timestamp with time zone NOT NULL,
    "Grip" numeric(5,2),
    "Shake" numeric(5,2),
    "UPower" numeric(5,2),
    "TemperatureCase" numeric(5,2),
    "TemperatureRoad" numeric(5,2),
    "HeightH2O" numeric(5,2),
    "HeightIce" numeric(5,2),
    "HeightSnow" numeric(5,2),
    "PercentICE" numeric(5,2),
    "PercentPGM" numeric(5,2),
    "RoadStatus" integer,
    "AngleToRoad" numeric(5,2),
    "TemperatureFreezePGM" numeric(5,2),
    "NeedCalibration" integer,
    "GPSLatitude" numeric(10,6),
    "GPSLongitude" numeric(10,6),
    "DistanceToSurface" numeric(12,2),
    "IsGpsValid" boolean DEFAULT true
);


ALTER TABLE public."DSPDData" OWNER TO postgres;

--
-- Name: DSPDData_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."DSPDData_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."DSPDData_Id_seq" OWNER TO postgres;

--
-- Name: DSPDData_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."DSPDData_Id_seq" OWNED BY public."DSPDData"."Id";


--
-- Name: DustData; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."DustData" (
    "Id" integer NOT NULL,
    "SensorId" integer NOT NULL,
    "ReceivedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "DataTimestamp" timestamp with time zone NOT NULL,
    "PM10Act" numeric(10,2),
    "PM25Act" numeric(10,2),
    "PM1Act" numeric(10,2),
    "PM10AWG" numeric(10,2),
    "PM25AWG" numeric(10,2),
    "PM1AWG" numeric(10,2),
    "FlowProbe" numeric(10,2),
    "TemperatureProbe" numeric(10,2),
    "HumidityProbe" numeric(10,2),
    "LaserStatus" integer,
    "SupplyVoltage" numeric(10,2)
);


ALTER TABLE public."DustData" OWNER TO postgres;

--
-- Name: DustData_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."DustData_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."DustData_Id_seq" OWNER TO postgres;

--
-- Name: DustData_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."DustData_Id_seq" OWNED BY public."DustData"."Id";


--
-- Name: IWSData; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."IWSData" (
    "Id" integer NOT NULL,
    "SensorId" integer NOT NULL,
    "ReceivedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "DataTimestamp" timestamp with time zone NOT NULL,
    "EnvTemperature" numeric(5,2),
    "Humidity" numeric(5,2),
    "DewPoint" numeric(5,2),
    "PressureHPa" numeric(7,2),
    "PressureQNHHPa" numeric(7,2),
    "PressureMmHg" numeric(7,2),
    "WindSpeed" numeric(5,2),
    "WindDirection" numeric(6,2),
    "WindVSound" numeric(6,2),
    "PrecipitationType" integer,
    "PrecipitationIntensity" numeric(5,2),
    "PrecipitationQuantity" numeric(5,2),
    "PrecipitationElapsed" integer,
    "PrecipitationPeriod" integer,
    "CO2Level" numeric(6,2),
    "SupplyVoltage" numeric(5,1),
    "Latitude" numeric(10,6),
    "Longitude" numeric(10,6),
    "Altitude" numeric(7,2),
    "KSP" integer,
    "GPSSpeed" numeric(5,1),
    "AccelerationStDev" numeric(5,2),
    "Roll" numeric(5,1),
    "Pitch" numeric(5,1),
    "WeAreFine" integer
);


ALTER TABLE public."IWSData" OWNER TO postgres;

--
-- Name: IWSData_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."IWSData_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."IWSData_Id_seq" OWNER TO postgres;

--
-- Name: IWSData_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."IWSData_Id_seq" OWNED BY public."IWSData"."Id";


--
-- Name: MUEKSData; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MUEKSData" (
    "Id" integer NOT NULL,
    "SensorId" integer NOT NULL,
    "ReceivedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "DataTimestamp" timestamp with time zone NOT NULL,
    "TemperatureBox" numeric(5,2),
    "UPowerIn12B" numeric(5,2),
    "UOut12B" numeric(5,2),
    "IOut12B" numeric(5,2),
    "IOut48B" numeric(5,2),
    "UAkb" numeric(5,2),
    "IAkb" numeric(5,2),
    "Sens220B" integer,
    "WhAkb" numeric(10,2),
    "VisibleRange" numeric(10,2),
    "DoorStatus" integer,
    "TdsH" character varying(50),
    "TdsTds" character varying(50),
    "TkosaT1" character varying(50),
    "TkosaT3" character varying(50)
);


ALTER TABLE public."MUEKSData" OWNER TO postgres;

--
-- Name: MUEKSData_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."MUEKSData_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."MUEKSData_Id_seq" OWNER TO postgres;

--
-- Name: MUEKSData_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."MUEKSData_Id_seq" OWNED BY public."MUEKSData"."Id";


--
-- Name: MonitoringPost; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MonitoringPost" (
    "Id" integer NOT NULL,
    "Name" character varying(255) NOT NULL,
    "Description" text,
    "Longitude" double precision,
    "Latitude" double precision,
    "IsMobile" boolean DEFAULT false NOT NULL,
    "IsActive" boolean DEFAULT true NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "UpdatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT chk_monitoringpost_coordinates_valid CHECK (((("Longitude" IS NULL) AND ("Latitude" IS NULL)) OR ((("Longitude" >= ('-180'::integer)::double precision) AND ("Longitude" <= (180)::double precision)) AND (("Latitude" >= ('-90'::integer)::double precision) AND ("Latitude" <= (90)::double precision)))))
);


ALTER TABLE public."MonitoringPost" OWNER TO postgres;

--
-- Name: MonitoringPost_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."MonitoringPost_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."MonitoringPost_Id_seq" OWNER TO postgres;

--
-- Name: MonitoringPost_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."MonitoringPost_Id_seq" OWNED BY public."MonitoringPost"."Id";


--
-- Name: Sensor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Sensor" (
    "Id" integer NOT NULL,
    "SensorTypeId" integer NOT NULL,
    "MonitoringPostId" integer,
    "Longitude" double precision,
    "Latitude" double precision,
    "SerialNumber" character varying(64) NOT NULL,
    "EndPointsName" character varying(255) NOT NULL,
    "Url" text NOT NULL,
    "CheckIntervalSeconds" integer DEFAULT 300 NOT NULL,
    "LastActivityUTC" timestamp with time zone,
    "CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "IsActive" boolean DEFAULT true NOT NULL,
    CONSTRAINT chk_sensor_coordinates_valid CHECK (((("Longitude" IS NULL) AND ("Latitude" IS NULL)) OR ((("Longitude" >= ('-180'::integer)::double precision) AND ("Longitude" <= (180)::double precision)) AND (("Latitude" >= ('-90'::integer)::double precision) AND ("Latitude" <= (90)::double precision)))))
);


ALTER TABLE public."Sensor" OWNER TO postgres;

--
-- Name: SensorError; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SensorError" (
    "Id" integer NOT NULL,
    "SensorId" integer NOT NULL,
    "ErrorLevel" character varying(20) NOT NULL,
    "ErrorMessage" text NOT NULL,
    "StackTrace" text,
    "ErrorSource" character varying(255),
    "ExceptionType" character varying(255),
    "CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "AdditionalData" jsonb
);


ALTER TABLE public."SensorError" OWNER TO postgres;

--
-- Name: SensorError_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."SensorError_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."SensorError_Id_seq" OWNER TO postgres;

--
-- Name: SensorError_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."SensorError_Id_seq" OWNED BY public."SensorError"."Id";


--
-- Name: SensorResults; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SensorResults" (
    "Id" integer NOT NULL,
    "SensorId" integer NOT NULL,
    "CheckedAt" timestamp with time zone NOT NULL,
    "StatusCode" integer NOT NULL,
    "ResponseBody" jsonb,
    "ResponseTimeMs" bigint NOT NULL,
    "IsSuccess" boolean NOT NULL
);


ALTER TABLE public."SensorResults" OWNER TO postgres;

--
-- Name: SensorResults_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."SensorResults_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."SensorResults_Id_seq" OWNER TO postgres;

--
-- Name: SensorResults_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."SensorResults_Id_seq" OWNED BY public."SensorResults"."Id";


--
-- Name: SensorType; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SensorType" (
    "Id" integer NOT NULL,
    "SensorTypeName" character varying(20) NOT NULL,
    "Description" text NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public."SensorType" OWNER TO postgres;

--
-- Name: SensorType_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."SensorType_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."SensorType_Id_seq" OWNER TO postgres;

--
-- Name: SensorType_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."SensorType_Id_seq" OWNED BY public."SensorType"."Id";


--
-- Name: Sensor_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."Sensor_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."Sensor_Id_seq" OWNER TO postgres;

--
-- Name: Sensor_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."Sensor_Id_seq" OWNED BY public."Sensor"."Id";


--
-- Name: Snapshots; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Snapshots" (
    "Id" integer NOT NULL,
    "CameraId" integer NOT NULL,
    "FilePath" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Snapshots" OWNER TO postgres;

--
-- Name: Snapshots_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Snapshots" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Snapshots_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "UserName" character varying(100) NOT NULL,
    "PasswordHash" text NOT NULL,
    "Salt" text NOT NULL,
    "Role" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: WorkerConfiguration; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."WorkerConfiguration" (
    "Id" integer NOT NULL,
    "Key" character varying(100) NOT NULL,
    "Value" text NOT NULL,
    "DataType" character varying(50) NOT NULL,
    "Description" text,
    "LastModified" timestamp with time zone DEFAULT now() NOT NULL,
    "ModifiedBy" character varying(100),
    "IsActive" boolean DEFAULT true NOT NULL,
    CONSTRAINT "WorkerConfiguration_DataType_check" CHECK ((("DataType")::text = ANY ((ARRAY['boolean'::character varying, 'integer'::character varying, 'string'::character varying, 'decimal'::character varying, 'json'::character varying])::text[])))
);


ALTER TABLE public."WorkerConfiguration" OWNER TO postgres;

--
-- Name: WorkerConfiguration_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."WorkerConfiguration_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."WorkerConfiguration_Id_seq" OWNER TO postgres;

--
-- Name: WorkerConfiguration_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."WorkerConfiguration_Id_seq" OWNED BY public."WorkerConfiguration"."Id";


--
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- Name: vw_dov_data_full; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_dov_data_full AS
 SELECT dd."Id" AS dov_data_id,
    dd."ReceivedAt" AS received_at,
    dd."DataTimestamp" AS data_timestamp,
    dd."VisibleRange" AS visible_range,
    dd."BrightFlag" AS bright_flag,
    s."Id" AS sensor_id,
    s."Longitude" AS sensor_longitude,
    s."Latitude" AS sensor_latitude,
    s."SerialNumber" AS serial_number,
    s."EndPointsName" AS endpoint_name,
    s."Url" AS sensor_url,
    s."CheckIntervalSeconds" AS check_interval_seconds,
    s."LastActivityUTC" AS last_activity_utc,
    s."IsActive" AS sensor_is_active,
    st."Id" AS sensor_type_id,
    st."SensorTypeName" AS sensor_type_name,
    st."Description" AS sensor_type_description,
    mp."Id" AS post_id,
    mp."Name" AS post_name,
    mp."Description" AS post_description,
    mp."IsMobile" AS post_is_mobile,
    mp."IsActive" AS post_is_active
   FROM (((public."DOVData" dd
     LEFT JOIN public."Sensor" s ON ((dd."SensorId" = s."Id")))
     LEFT JOIN public."SensorType" st ON ((s."SensorTypeId" = st."Id")))
     LEFT JOIN public."MonitoringPost" mp ON ((s."MonitoringPostId" = mp."Id")));


ALTER VIEW public.vw_dov_data_full OWNER TO postgres;

--
-- Name: vw_dspd_data_full; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_dspd_data_full AS
 SELECT dd."Id" AS dspd_data_id,
    dd."ReceivedAt" AS received_at,
    dd."DataTimestamp" AS data_timestamp,
    dd."Grip" AS grip_coefficient,
    dd."Shake" AS shake_level,
    dd."UPower" AS voltage_power,
    dd."TemperatureCase" AS case_temperature,
    dd."TemperatureRoad" AS road_temperature,
    dd."HeightH2O" AS water_height,
    dd."HeightIce" AS ice_height,
    dd."HeightSnow" AS snow_height,
    dd."PercentICE" AS ice_percentage,
    dd."PercentPGM" AS pgm_percentage,
    dd."RoadStatus" AS road_status_code,
    dd."AngleToRoad" AS road_angle,
    dd."TemperatureFreezePGM" AS freeze_temperature,
    dd."NeedCalibration" AS calibration_needed,
    dd."GPSLatitude" AS gps_latitude,
    dd."GPSLongitude" AS gps_longitude,
    dd."IsGpsValid" AS gps_valid,
    dd."DistanceToSurface" AS distance_to_surface,
    s."Id" AS sensor_id,
    s."Longitude" AS sensor_longitude,
    s."Latitude" AS sensor_latitude,
    s."SerialNumber" AS serial_number,
    s."EndPointsName" AS endpoint_name,
    s."Url" AS sensor_url,
    s."CheckIntervalSeconds" AS check_interval_seconds,
    s."LastActivityUTC" AS last_activity_utc,
    s."IsActive" AS sensor_is_active,
    st."Id" AS sensor_type_id,
    st."SensorTypeName" AS sensor_type_name,
    st."Description" AS sensor_type_description,
    mp."Id" AS post_id,
    mp."Name" AS post_name,
    mp."Description" AS post_description,
    mp."IsMobile" AS post_is_mobile,
    mp."IsActive" AS post_is_active
   FROM (((public."DSPDData" dd
     LEFT JOIN public."Sensor" s ON ((dd."SensorId" = s."Id")))
     LEFT JOIN public."SensorType" st ON ((s."SensorTypeId" = st."Id")))
     LEFT JOIN public."MonitoringPost" mp ON ((s."MonitoringPostId" = mp."Id")));


ALTER VIEW public.vw_dspd_data_full OWNER TO postgres;

--
-- Name: vw_dust_data_full; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_dust_data_full AS
 SELECT dd."Id" AS dust_data_id,
    dd."ReceivedAt" AS received_at,
    dd."DataTimestamp" AS data_timestamp,
    dd."PM10Act" AS pm10act,
    dd."PM25Act" AS pm25act,
    dd."PM1Act" AS pm1act,
    dd."PM10AWG" AS pm10awg,
    dd."PM25AWG" AS pm25awg,
    dd."PM1AWG" AS pm1awg,
    dd."FlowProbe" AS flowprobe,
    dd."TemperatureProbe" AS temperatureprobe,
    dd."HumidityProbe" AS humidityprobe,
    dd."LaserStatus" AS laserstatus,
    dd."SupplyVoltage" AS supplyvoltage,
    s."Id" AS sensor_id,
    s."Longitude" AS sensor_longitude,
    s."Latitude" AS sensor_latitude,
    s."SerialNumber" AS serial_number,
    s."EndPointsName" AS endpoint_name,
    s."Url" AS sensor_url,
    s."CheckIntervalSeconds" AS check_interval_seconds,
    s."LastActivityUTC" AS last_activity_utc,
    s."IsActive" AS sensor_is_active,
    st."Id" AS sensor_type_id,
    st."SensorTypeName" AS sensor_type_name,
    st."Description" AS sensor_type_description,
    mp."Id" AS post_id,
    mp."Name" AS post_name,
    mp."Description" AS post_description,
    mp."IsMobile" AS post_is_mobile,
    mp."IsActive" AS post_is_active
   FROM (((public."DustData" dd
     LEFT JOIN public."Sensor" s ON ((dd."SensorId" = s."Id")))
     LEFT JOIN public."SensorType" st ON ((s."SensorTypeId" = st."Id")))
     LEFT JOIN public."MonitoringPost" mp ON ((s."MonitoringPostId" = mp."Id")));


ALTER VIEW public.vw_dust_data_full OWNER TO postgres;

--
-- Name: vw_iws_data_full; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_iws_data_full AS
 SELECT iws."Id" AS iws_data_id,
    iws."ReceivedAt" AS received_at,
    iws."DataTimestamp" AS data_timestamp,
    iws."EnvTemperature" AS environment_temperature,
    iws."Humidity" AS humidity_percentage,
    iws."DewPoint" AS dew_point,
    iws."PressureHPa" AS pressure_hpa,
    iws."PressureQNHHPa" AS pressure_qnh_hpa,
    iws."PressureMmHg" AS pressure_mmhg,
    iws."WindSpeed" AS wind_speed,
    iws."WindDirection" AS wind_direction,
    iws."WindVSound" AS wind_vs_sound,
    iws."PrecipitationType" AS precipitation_type,
    iws."PrecipitationIntensity" AS precipitation_intensity,
    iws."PrecipitationQuantity" AS precipitation_quantity,
    iws."PrecipitationElapsed" AS precipitation_elapsed,
    iws."PrecipitationPeriod" AS precipitation_period,
    iws."CO2Level" AS co2_level,
    iws."SupplyVoltage" AS supply_voltage,
    iws."Latitude" AS iws_latitude,
    iws."Longitude" AS iws_longitude,
    iws."Altitude" AS altitude,
    iws."KSP" AS ksp_value,
    iws."GPSSpeed" AS gps_speed,
    iws."AccelerationStDev" AS acceleration_std_dev,
    iws."Roll" AS roll_angle,
    iws."Pitch" AS pitch_angle,
    iws."WeAreFine" AS status_ok,
    s."Id" AS sensor_id,
    s."Longitude" AS sensor_longitude,
    s."Latitude" AS sensor_latitude,
    s."SerialNumber" AS serial_number,
    s."EndPointsName" AS endpoint_name,
    s."Url" AS sensor_url,
    s."CheckIntervalSeconds" AS check_interval_seconds,
    s."LastActivityUTC" AS last_activity_utc,
    s."IsActive" AS sensor_is_active,
    st."Id" AS sensor_type_id,
    st."SensorTypeName" AS sensor_type_name,
    st."Description" AS sensor_type_description,
    mp."Id" AS post_id,
    mp."Name" AS post_name,
    mp."Description" AS post_description,
    mp."IsMobile" AS post_is_mobile,
    mp."IsActive" AS post_is_active
   FROM (((public."IWSData" iws
     LEFT JOIN public."Sensor" s ON ((iws."SensorId" = s."Id")))
     LEFT JOIN public."SensorType" st ON ((s."SensorTypeId" = st."Id")))
     LEFT JOIN public."MonitoringPost" mp ON ((s."MonitoringPostId" = mp."Id")));


ALTER VIEW public.vw_iws_data_full OWNER TO postgres;

--
-- Name: vw_mueks_data_full; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_mueks_data_full AS
 SELECT pd."Id" AS mueks_data_id,
    pd."ReceivedAt" AS received_at,
    pd."DataTimestamp" AS data_timestamp,
    pd."TemperatureBox" AS temperature_box,
    pd."UPowerIn12B" AS voltage_power_in_12b,
    pd."UOut12B" AS voltage_out_12b,
    pd."IOut12B" AS current_out_12b,
    pd."IOut48B" AS current_out_48b,
    pd."UAkb" AS voltage_akb,
    pd."IAkb" AS current_akb,
    pd."Sens220B" AS sensor_220b,
    pd."WhAkb" AS watt_hours_akb,
    pd."VisibleRange" AS visible_range,
    pd."DoorStatus" AS door_status,
    pd."TdsH" AS tds_h,
    pd."TdsTds" AS tds_tds,
    pd."TkosaT1" AS tkosa_t1,
    pd."TkosaT3" AS tkosa_t3,
    s."Id" AS sensor_id,
    s."Longitude" AS sensor_longitude,
    s."Latitude" AS sensor_latitude,
    s."SerialNumber" AS serial_number,
    s."EndPointsName" AS endpoint_name,
    s."Url" AS sensor_url,
    s."CheckIntervalSeconds" AS check_interval_seconds,
    s."LastActivityUTC" AS last_activity_utc,
    s."IsActive" AS sensor_is_active,
    st."Id" AS sensor_type_id,
    st."SensorTypeName" AS sensor_type_name,
    st."Description" AS sensor_type_description,
    mp."Id" AS post_id,
    mp."Name" AS post_name,
    mp."Description" AS post_description,
    mp."IsMobile" AS post_is_mobile,
    mp."IsActive" AS post_is_active
   FROM (((public."MUEKSData" pd
     LEFT JOIN public."Sensor" s ON ((pd."SensorId" = s."Id")))
     LEFT JOIN public."SensorType" st ON ((s."SensorTypeId" = st."Id")))
     LEFT JOIN public."MonitoringPost" mp ON ((s."MonitoringPostId" = mp."Id")));


ALTER VIEW public.vw_mueks_data_full OWNER TO postgres;

--
-- Name: vw_pinger_data_full; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_pinger_data_full AS
 SELECT pd."Id" AS pinger_data_id,
    pd."ReceivedAt" AS received_at,
    pd."DataTimestamp" AS data_timestamp,
    pd."TemperatureBox" AS temperature_box,
    pd."UPowerIn12B" AS voltage_power_in_12b,
    pd."UOut12B" AS voltage_out_12b,
    pd."IOut12B" AS current_out_12b,
    pd."IOut48B" AS current_out_48b,
    pd."UAkb" AS voltage_akb,
    pd."IAkb" AS current_akb,
    pd."Sens220B" AS sensor_220b,
    pd."WhAkb" AS watt_hours_akb,
    pd."VisibleRange" AS visible_range,
    pd."DoorStatus" AS door_status,
    pd."TdsH" AS tds_h,
    pd."TdsTds" AS tds_tds,
    pd."TkosaT1" AS tkosa_t1,
    pd."TkosaT3" AS tkosa_t3,
    s."Longitude" AS sensor_longitude,
    s."Latitude" AS sensor_latitude,
    s."SerialNumber" AS serial_number,
    s."EndPointsName" AS endpoint_name,
    s."Url" AS sensor_url,
    s."CheckIntervalSeconds" AS check_interval_seconds,
    s."LastActivityUTC" AS last_activity_utc,
    s."IsActive" AS sensor_is_active,
    st."SensorTypeName" AS sensor_type_name,
    st."Description" AS sensor_type_description,
    mp."Name" AS post_name,
    mp."Description" AS post_description,
    mp."IsMobile" AS post_is_mobile,
    mp."IsActive" AS post_is_active
   FROM (((public."MUEKSData" pd
     LEFT JOIN public."Sensor" s ON ((pd."SensorId" = s."Id")))
     LEFT JOIN public."SensorType" st ON ((s."SensorTypeId" = st."Id")))
     LEFT JOIN public."MonitoringPost" mp ON ((s."MonitoringPostId" = mp."Id")));


ALTER VIEW public.vw_pinger_data_full OWNER TO postgres;

--
-- Name: vw_sensor_errors_full; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_sensor_errors_full AS
 SELECT se."Id" AS error_id,
    se."ErrorLevel" AS error_level,
    se."ErrorMessage" AS error_message,
    se."StackTrace" AS stack_trace,
    se."ErrorSource" AS error_source,
    se."ExceptionType" AS exception_type,
    se."CreatedAt" AS error_created_at,
    se."AdditionalData" AS additional_data,
    s."Id" AS sensor_id,
    s."Longitude" AS sensor_longitude,
    s."Latitude" AS sensor_latitude,
    s."SerialNumber" AS serial_number,
    s."EndPointsName" AS endpoint_name,
    s."Url" AS sensor_url,
    s."CheckIntervalSeconds" AS check_interval_seconds,
    s."LastActivityUTC" AS last_activity_utc,
    s."IsActive" AS sensor_is_active,
    st."Id" AS sensor_type_id,
    st."SensorTypeName" AS sensor_type_name,
    st."Description" AS sensor_type_description,
    mp."Id" AS post_id,
    mp."Name" AS post_name,
    mp."Description" AS post_description,
    mp."Longitude" AS post_longitude,
    mp."Latitude" AS post_latitude,
    mp."IsMobile" AS post_is_mobile,
    mp."IsActive" AS post_is_active,
    mp."UpdatedAt" AS post_updated_at
   FROM (((public."SensorError" se
     LEFT JOIN public."Sensor" s ON ((se."SensorId" = s."Id")))
     LEFT JOIN public."SensorType" st ON ((s."SensorTypeId" = st."Id")))
     LEFT JOIN public."MonitoringPost" mp ON ((s."MonitoringPostId" = mp."Id")));


ALTER VIEW public.vw_sensor_errors_full OWNER TO postgres;

--
-- Name: vw_sensor_results_full; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_sensor_results_full AS
 SELECT sr."Id" AS result_id,
    sr."CheckedAt" AS checked_at,
    sr."StatusCode" AS status_code,
    sr."ResponseBody" AS response_body,
    sr."ResponseTimeMs" AS response_time_ms,
    sr."IsSuccess" AS is_success,
    s."Id" AS sensor_id,
    s."Longitude" AS sensor_longitude,
    s."Latitude" AS sensor_latitude,
    s."SerialNumber" AS serial_number,
    s."EndPointsName" AS endpoint_name,
    s."Url" AS sensor_url,
    s."CheckIntervalSeconds" AS check_interval_seconds,
    s."LastActivityUTC" AS last_activity_utc,
    s."IsActive" AS sensor_is_active,
    st."Id" AS sensor_type_id,
    st."SensorTypeName" AS sensor_type_name,
    st."Description" AS sensor_type_description,
    mp."Id" AS post_id,
    mp."Name" AS post_name,
    mp."Description" AS post_description,
    mp."IsMobile" AS post_is_mobile,
    mp."IsActive" AS post_is_active
   FROM (((public."SensorResults" sr
     LEFT JOIN public."Sensor" s ON ((sr."SensorId" = s."Id")))
     LEFT JOIN public."SensorType" st ON ((s."SensorTypeId" = st."Id")))
     LEFT JOIN public."MonitoringPost" mp ON ((s."MonitoringPostId" = mp."Id")));


ALTER VIEW public.vw_sensor_results_full OWNER TO postgres;

--
-- Name: DOVData Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DOVData" ALTER COLUMN "Id" SET DEFAULT nextval('public."DOVData_Id_seq"'::regclass);


--
-- Name: DSPDData Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DSPDData" ALTER COLUMN "Id" SET DEFAULT nextval('public."DSPDData_Id_seq"'::regclass);


--
-- Name: DustData Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DustData" ALTER COLUMN "Id" SET DEFAULT nextval('public."DustData_Id_seq"'::regclass);


--
-- Name: IWSData Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."IWSData" ALTER COLUMN "Id" SET DEFAULT nextval('public."IWSData_Id_seq"'::regclass);


--
-- Name: MUEKSData Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MUEKSData" ALTER COLUMN "Id" SET DEFAULT nextval('public."MUEKSData_Id_seq"'::regclass);


--
-- Name: MonitoringPost Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MonitoringPost" ALTER COLUMN "Id" SET DEFAULT nextval('public."MonitoringPost_Id_seq"'::regclass);


--
-- Name: Sensor Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sensor" ALTER COLUMN "Id" SET DEFAULT nextval('public."Sensor_Id_seq"'::regclass);


--
-- Name: SensorError Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SensorError" ALTER COLUMN "Id" SET DEFAULT nextval('public."SensorError_Id_seq"'::regclass);


--
-- Name: SensorResults Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SensorResults" ALTER COLUMN "Id" SET DEFAULT nextval('public."SensorResults_Id_seq"'::regclass);


--
-- Name: SensorType Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SensorType" ALTER COLUMN "Id" SET DEFAULT nextval('public."SensorType_Id_seq"'::regclass);


--
-- Name: WorkerConfiguration Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WorkerConfiguration" ALTER COLUMN "Id" SET DEFAULT nextval('public."WorkerConfiguration_Id_seq"'::regclass);


--
-- Name: DOVData DOVData_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DOVData"
    ADD CONSTRAINT "DOVData_pkey" PRIMARY KEY ("Id");


--
-- Name: DSPDData DSPDData_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DSPDData"
    ADD CONSTRAINT "DSPDData_pkey" PRIMARY KEY ("Id");


--
-- Name: DustData DustData_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DustData"
    ADD CONSTRAINT "DustData_pkey" PRIMARY KEY ("Id");


--
-- Name: IWSData IWSData_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."IWSData"
    ADD CONSTRAINT "IWSData_pkey" PRIMARY KEY ("Id");


--
-- Name: MUEKSData MUEKSData_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MUEKSData"
    ADD CONSTRAINT "MUEKSData_pkey" PRIMARY KEY ("Id");


--
-- Name: MonitoringPost MonitoringPost_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MonitoringPost"
    ADD CONSTRAINT "MonitoringPost_pkey" PRIMARY KEY ("Id");


--
-- Name: AuditLogs PK_AuditLogs; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AuditLogs"
    ADD CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id");


--
-- Name: Cameras PK_Cameras; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Cameras"
    ADD CONSTRAINT "PK_Cameras" PRIMARY KEY ("Id");


--
-- Name: Snapshots PK_Snapshots; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Snapshots"
    ADD CONSTRAINT "PK_Snapshots" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- Name: SensorError SensorError_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SensorError"
    ADD CONSTRAINT "SensorError_pkey" PRIMARY KEY ("Id");


--
-- Name: SensorResults SensorResults_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SensorResults"
    ADD CONSTRAINT "SensorResults_pkey" PRIMARY KEY ("Id");


--
-- Name: SensorType SensorType_SensorTypeName_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SensorType"
    ADD CONSTRAINT "SensorType_SensorTypeName_key" UNIQUE ("SensorTypeName");


--
-- Name: SensorType SensorType_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SensorType"
    ADD CONSTRAINT "SensorType_pkey" PRIMARY KEY ("Id");


--
-- Name: Sensor Sensor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sensor"
    ADD CONSTRAINT "Sensor_pkey" PRIMARY KEY ("Id");


--
-- Name: WorkerConfiguration WorkerConfiguration_Key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WorkerConfiguration"
    ADD CONSTRAINT "WorkerConfiguration_Key_key" UNIQUE ("Key");


--
-- Name: WorkerConfiguration WorkerConfiguration_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WorkerConfiguration"
    ADD CONSTRAINT "WorkerConfiguration_pkey" PRIMARY KEY ("Id");


--
-- Name: IX_AuditLogs_Action; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AuditLogs_Action" ON public."AuditLogs" USING btree ("Action");


--
-- Name: IX_AuditLogs_ChangeType; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AuditLogs_ChangeType" ON public."AuditLogs" USING btree ("ChangeType");


--
-- Name: IX_AuditLogs_EntityId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AuditLogs_EntityId" ON public."AuditLogs" USING btree ("EntityId");


--
-- Name: IX_AuditLogs_EntityType; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AuditLogs_EntityType" ON public."AuditLogs" USING btree ("EntityType");


--
-- Name: IX_AuditLogs_Timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AuditLogs_Timestamp" ON public."AuditLogs" USING btree ("Timestamp");


--
-- Name: IX_AuditLogs_Type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AuditLogs_Type" ON public."AuditLogs" USING btree ("Type");


--
-- Name: IX_AuditLogs_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AuditLogs_UserId" ON public."AuditLogs" USING btree ("UserId");


--
-- Name: IX_AuditLogs_UserName; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AuditLogs_UserName" ON public."AuditLogs" USING btree ("UserName");


--
-- Name: IX_Cameras_MonitoringPostId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Cameras_MonitoringPostId" ON public."Cameras" USING btree ("MonitoringPostId");


--
-- Name: IX_Snapshots_CameraId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Snapshots_CameraId" ON public."Snapshots" USING btree ("CameraId");


--
-- Name: IX_Users_UserName; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_UserName" ON public."Users" USING btree ("UserName");


--
-- Name: idx_DustData_DataTimestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "idx_DustData_DataTimestamp" ON public."DustData" USING btree ("DataTimestamp");


--
-- Name: idx_DustData_SensorId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "idx_DustData_SensorId" ON public."DustData" USING btree ("SensorId");


--
-- Name: idx_dovdata_sensor_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dovdata_sensor_timestamp ON public."DOVData" USING btree ("SensorId", "DataTimestamp");


--
-- Name: idx_dovdata_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dovdata_timestamp ON public."DOVData" USING btree ("DataTimestamp");


--
-- Name: idx_dovdata_visibility; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dovdata_visibility ON public."DOVData" USING btree ("VisibleRange");


--
-- Name: idx_dspddata_grip; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dspddata_grip ON public."DSPDData" USING btree ("Grip");


--
-- Name: idx_dspddata_roadstatus; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dspddata_roadstatus ON public."DSPDData" USING btree ("RoadStatus");


--
-- Name: idx_dspddata_sensor_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dspddata_sensor_timestamp ON public."DSPDData" USING btree ("SensorId", "DataTimestamp");


--
-- Name: idx_dspddata_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dspddata_timestamp ON public."DSPDData" USING btree ("DataTimestamp");


--
-- Name: idx_iwsdata_sensor_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_iwsdata_sensor_timestamp ON public."IWSData" USING btree ("SensorId", "DataTimestamp");


--
-- Name: idx_iwsdata_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_iwsdata_timestamp ON public."IWSData" USING btree ("DataTimestamp");


--
-- Name: idx_iwsdata_weather; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_iwsdata_weather ON public."IWSData" USING btree ("EnvTemperature", "Humidity", "WindSpeed");


--
-- Name: idx_monitoringpost_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_monitoringpost_active ON public."MonitoringPost" USING btree ("IsActive");


--
-- Name: idx_monitoringpost_coordinates; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_monitoringpost_coordinates ON public."MonitoringPost" USING btree ("Longitude", "Latitude");


--
-- Name: idx_monitoringpost_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_monitoringpost_created_at ON public."MonitoringPost" USING btree ("CreatedAt");


--
-- Name: idx_monitoringpost_mobile; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_monitoringpost_mobile ON public."MonitoringPost" USING btree ("IsMobile");


--
-- Name: idx_monitoringpost_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_monitoringpost_name ON public."MonitoringPost" USING btree ("Name");


--
-- Name: idx_pingerdata_sensor_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_pingerdata_sensor_timestamp ON public."MUEKSData" USING btree ("SensorId", "DataTimestamp");


--
-- Name: idx_pingerdata_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_pingerdata_timestamp ON public."MUEKSData" USING btree ("DataTimestamp");


--
-- Name: idx_pingerdata_visibility; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_pingerdata_visibility ON public."MUEKSData" USING btree ("VisibleRange");


--
-- Name: idx_sensor_active_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sensor_active_type ON public."Sensor" USING btree ("IsActive", "SensorTypeId");


--
-- Name: idx_sensor_check_interval; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sensor_check_interval ON public."Sensor" USING btree ("CheckIntervalSeconds");


--
-- Name: idx_sensor_error_created; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sensor_error_created ON public."SensorError" USING btree ("CreatedAt");


--
-- Name: idx_sensor_error_level; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sensor_error_level ON public."SensorError" USING btree ("ErrorLevel");


--
-- Name: idx_sensor_error_sensor; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sensor_error_sensor ON public."SensorError" USING btree ("SensorId");


--
-- Name: idx_sensor_last_activity; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sensor_last_activity ON public."Sensor" USING btree ("LastActivityUTC");


--
-- Name: idx_sensor_monitoringpost; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sensor_monitoringpost ON public."Sensor" USING btree ("MonitoringPostId");


--
-- Name: idx_sensor_results_checked; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sensor_results_checked ON public."SensorResults" USING btree ("CheckedAt");


--
-- Name: idx_sensor_results_sensor; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sensor_results_sensor ON public."SensorResults" USING btree ("SensorId");


--
-- Name: idx_sensor_results_success; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sensor_results_success ON public."SensorResults" USING btree ("IsSuccess");


--
-- Name: idx_sensor_serial; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sensor_serial ON public."Sensor" USING btree ("SerialNumber");


--
-- Name: DOVData DOVData_SensorId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DOVData"
    ADD CONSTRAINT "DOVData_SensorId_fkey" FOREIGN KEY ("SensorId") REFERENCES public."Sensor"("Id") ON DELETE RESTRICT;


--
-- Name: DSPDData DSPDData_SensorId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DSPDData"
    ADD CONSTRAINT "DSPDData_SensorId_fkey" FOREIGN KEY ("SensorId") REFERENCES public."Sensor"("Id") ON DELETE RESTRICT;


--
-- Name: DustData DustData_SensorId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DustData"
    ADD CONSTRAINT "DustData_SensorId_fkey" FOREIGN KEY ("SensorId") REFERENCES public."Sensor"("Id") ON DELETE RESTRICT;


--
-- Name: AuditLogs FK_AuditLogs_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AuditLogs"
    ADD CONSTRAINT "FK_AuditLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE SET NULL;


--
-- Name: Cameras FK_Cameras_MonitoringPost_MonitoringPostId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Cameras"
    ADD CONSTRAINT "FK_Cameras_MonitoringPost_MonitoringPostId" FOREIGN KEY ("MonitoringPostId") REFERENCES public."MonitoringPost"("Id");


--
-- Name: Snapshots FK_Snapshots_Cameras_CameraId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Snapshots"
    ADD CONSTRAINT "FK_Snapshots_Cameras_CameraId" FOREIGN KEY ("CameraId") REFERENCES public."Cameras"("Id");


--
-- Name: IWSData IWSData_SensorId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."IWSData"
    ADD CONSTRAINT "IWSData_SensorId_fkey" FOREIGN KEY ("SensorId") REFERENCES public."Sensor"("Id") ON DELETE RESTRICT;


--
-- Name: MUEKSData MUEKSData_SensorId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MUEKSData"
    ADD CONSTRAINT "MUEKSData_SensorId_fkey" FOREIGN KEY ("SensorId") REFERENCES public."Sensor"("Id") ON DELETE RESTRICT;


--
-- Name: SensorError SensorError_SensorId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SensorError"
    ADD CONSTRAINT "SensorError_SensorId_fkey" FOREIGN KEY ("SensorId") REFERENCES public."Sensor"("Id") ON DELETE RESTRICT;


--
-- Name: SensorResults SensorResults_SensorId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SensorResults"
    ADD CONSTRAINT "SensorResults_SensorId_fkey" FOREIGN KEY ("SensorId") REFERENCES public."Sensor"("Id") ON DELETE RESTRICT;


--
-- Name: Sensor Sensor_MonitoringPostId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sensor"
    ADD CONSTRAINT "Sensor_MonitoringPostId_fkey" FOREIGN KEY ("MonitoringPostId") REFERENCES public."MonitoringPost"("Id") ON DELETE SET NULL;


--
-- Name: Sensor Sensor_SensorTypeId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sensor"
    ADD CONSTRAINT "Sensor_SensorTypeId_fkey" FOREIGN KEY ("SensorTypeId") REFERENCES public."SensorType"("Id") ON DELETE RESTRICT;


--
-- PostgreSQL database dump complete
--

\unrestrict m67YgIvnxfXj4KTITeB5QSRRx5LfAgsI7yKfOfPtxDtBDwNX9pmgZcbFLwHp83S

