CREATE TABLE public."AuditLogs" (
    "Id" integer NOT NULL,
    "Type" integer NOT NULL,
    "Timestamp" timestamp with time zone NOT NULL,
    "UserId" integer,
    "UserName" character varying(100),
    "Action" character varying(200),
    "Details" character varying(1000),
    "TargetId" integer,
    "HttpMethod" character varying(10),
    "Url" character varying(500),
    "IpAddress" character varying(50),
    "UserAgent" character varying(500),
    "IsSuccess" boolean,
    "ExecutionTimeMs" bigint,
    "EntityType" character varying(200),
    "EntityId" integer,
    "ChangeType" character varying(50),
    "OriginalValues" jsonb,
    "NewValues" jsonb,
    "ChangedProperties" jsonb
);


ALTER TABLE public."AuditLogs" OWNER TO postgres;

--
-- Name: AuditLogs_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."AuditLogs" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."AuditLogs_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Cameras; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Cameras" (
    "Id" integer NOT NULL,
    "Name" character varying(200) NOT NULL,
    "WebUrl" text,
    "RtspUrl" text NOT NULL,
    "PollingInterval" integer CONSTRAINT "Cameras_Port_not_null" NOT NULL,
    "Username" text,
    "Password" text,
    "IsPtzSupported" boolean NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "ApiRequest" text,
    "FdaId" text,
    "InstallationLocation" text,
    "MonitoringPostId" integer,
    "Picket" text,
    "SerialNumber" text
);


ALTER TABLE public."Cameras" OWNER TO postgres;

--
-- Name: Cameras_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Cameras" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Cameras_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: DOVData; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."DOVData" (
    "Id" integer NOT NULL,
    "SensorId" integer NOT NULL,
    "ReceivedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "DataTimestamp" timestamp with time zone NOT NULL,
    "VisibleRange" numeric(10,2),
    "BrightFlag" integer,
    "PollingSessionId" uuid,
    "MonitoringPostId" integer
);


ALTER TABLE public."DOVData" OWNER TO postgres;

--
-- Name: COLUMN "DOVData"."PollingSessionId"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."DOVData"."PollingSessionId" IS 'Γò¿├¡Γòñ├╝Γòñ├»Γò¿ΓòùΓò¿ΓòæΓò¿Γûæ Γò¿Γò£Γò¿Γûæ Γòñ├╝Γò¿ΓòíΓòñ├╝Γòñ├╝Γò¿ΓòòΓòñ├ä Γò¿Γò¢Γò¿ΓöÉΓòñ├çΓò¿Γò¢Γòñ├╝Γò¿Γûæ, Γò¿Γûô Γòñ├çΓò¿ΓûæΓò¿Γò¥Γò¿ΓòæΓò¿ΓûæΓòñ├á Γò¿ΓòæΓò¿Γò¢Γòñ├⌐Γò¿Γò¢Γòñ├çΓò¿Γò¢Γò¿Γòú Γò¿ΓûÆΓòñ├»Γò¿ΓòùΓò¿Γòò Γò¿ΓöÉΓò¿Γò¢Γò¿ΓòùΓòñ├óΓòñ├ºΓò¿ΓòíΓò¿Γò£Γòñ├» Γòñ├¼Γòñ├⌐Γò¿Γòò Γò¿ΓöñΓò¿ΓûæΓò¿Γò£Γò¿Γò£Γòñ├»Γò¿Γòí';


--
-- Name: COLUMN "DOVData"."MonitoringPostId"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."DOVData"."MonitoringPostId" IS 'Γò¿├╢Γò¿ΓòíΓò¿Γò£Γò¿Γò¢Γòñ├çΓò¿Γò¥Γò¿ΓûæΓò¿ΓòùΓò¿ΓòòΓò¿ΓòûΓò¿Γò¢Γò¿ΓûôΓò¿ΓûæΓò¿Γò£Γò¿Γò£Γò¿Γò¢Γò¿Γòí Γò¿ΓöÉΓò¿Γò¢Γò¿ΓòùΓò¿Γòí ID Γò¿ΓöÉΓò¿Γò¢Γòñ├╝Γòñ├⌐Γò¿Γûæ Γò¿ΓöñΓò¿ΓòùΓòñ├à Γòñ├óΓòñ├╝Γò¿ΓòæΓò¿Γò¢Γòñ├çΓò¿ΓòíΓò¿Γò£Γò¿ΓòòΓòñ├à Γò¿ΓòûΓò¿ΓûæΓò¿ΓöÉΓòñ├çΓò¿Γò¢Γòñ├╝Γò¿Γò¢Γò¿Γûô';


--
-- Name: DOVData_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."DOVData_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."DOVData_Id_seq" OWNER TO postgres;

--
-- Name: DOVData_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."DOVData_Id_seq" OWNED BY public."DOVData"."Id";


--
-- Name: DSPDData; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."DSPDData" (
    "Id" integer NOT NULL,
    "SensorId" integer NOT NULL,
    "ReceivedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "DataTimestamp" timestamp with time zone NOT NULL,
    "Grip" numeric(5,2),
    "Shake" numeric(5,2),
    "UPower" numeric(5,2),
    "TemperatureCase" numeric(5,2),
    "TemperatureRoad" numeric(5,2),
    "HeightH2O" numeric(5,2),
    "HeightIce" numeric(5,2),
    "HeightSnow" numeric(5,2),
    "PercentICE" numeric(5,2),
    "PercentPGM" numeric(5,2),
    "RoadStatus" integer,
    "AngleToRoad" numeric(5,2),
    "TemperatureFreezePGM" numeric(5,2),
    "NeedCalibration" integer,
    "GPSLatitude" numeric(10,6),
    "GPSLongitude" numeric(10,6),
    "DistanceToSurface" numeric(12,2),
    "IsGpsValid" boolean DEFAULT true,
    "PollingSessionId" uuid,
    "MonitoringPostId" integer
);


ALTER TABLE public."DSPDData" OWNER TO postgres;

--
-- Name: COLUMN "DSPDData"."PollingSessionId"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."DSPDData"."PollingSessionId" IS 'Γò¿├¡Γòñ├╝Γòñ├»Γò¿ΓòùΓò¿ΓòæΓò¿Γûæ Γò¿Γò£Γò¿Γûæ Γòñ├╝Γò¿ΓòíΓòñ├╝Γòñ├╝Γò¿ΓòòΓòñ├ä Γò¿Γò¢Γò¿ΓöÉΓòñ├çΓò¿Γò¢Γòñ├╝Γò¿Γûæ, Γò¿Γûô Γòñ├çΓò¿ΓûæΓò¿Γò¥Γò¿ΓòæΓò¿ΓûæΓòñ├á Γò¿ΓòæΓò¿Γò¢Γòñ├⌐Γò¿Γò¢Γòñ├çΓò¿Γò¢Γò¿Γòú Γò¿ΓûÆΓòñ├»Γò¿ΓòùΓò¿Γòò Γò¿ΓöÉΓò¿Γò¢Γò¿ΓòùΓòñ├óΓòñ├ºΓò¿ΓòíΓò¿Γò£Γòñ├» Γòñ├¼Γòñ├⌐Γò¿Γòò Γò¿ΓöñΓò¿ΓûæΓò¿Γò£Γò¿Γò£Γòñ├»Γò¿Γòí';


--
-- Name: COLUMN "DSPDData"."MonitoringPostId"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."DSPDData"."MonitoringPostId" IS 'Γò¿├╢Γò¿ΓòíΓò¿Γò£Γò¿Γò¢Γòñ├çΓò¿Γò¥Γò¿ΓûæΓò¿ΓòùΓò¿ΓòòΓò¿ΓòûΓò¿Γò¢Γò¿ΓûôΓò¿ΓûæΓò¿Γò£Γò¿Γò£Γò¿Γò¢Γò¿Γòí Γò¿ΓöÉΓò¿Γò¢Γò¿ΓòùΓò¿Γòí ID Γò¿ΓöÉΓò¿Γò¢Γòñ├╝Γòñ├⌐Γò¿Γûæ Γò¿ΓöñΓò¿ΓòùΓòñ├à Γòñ├óΓòñ├╝Γò¿ΓòæΓò¿Γò¢Γòñ├çΓò¿ΓòíΓò¿Γò£Γò¿ΓòòΓòñ├à Γò¿ΓòûΓò¿ΓûæΓò¿ΓöÉΓòñ├çΓò¿Γò¢Γòñ├╝Γò¿Γò¢Γò¿Γûô';


--
-- Name: DSPDData_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."DSPDData_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."DSPDData_Id_seq" OWNER TO postgres;

--
-- Name: DSPDData_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."DSPDData_Id_seq" OWNED BY public."DSPDData"."Id";


--
-- Name: DustData; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."DustData" (
    "Id" integer NOT NULL,
    "SensorId" integer NOT NULL,
    "ReceivedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "DataTimestamp" timestamp with time zone NOT NULL,
    "PM10Act" numeric(10,2),
    "PM25Act" numeric(10,2),
    "PM1Act" numeric(10,2),
    "PM10AWG" numeric(10,2),
    "PM25AWG" numeric(10,2),
    "PM1AWG" numeric(10,2),
    "FlowProbe" numeric(10,2),
    "TemperatureProbe" numeric(10,2),
    "HumidityProbe" numeric(10,2),
    "LaserStatus" integer,
    "SupplyVoltage" numeric(10,2),
    "PollingSessionId" uuid,
    "MonitoringPostId" integer
);


ALTER TABLE public."DustData" OWNER TO postgres;

--
-- Name: COLUMN "DustData"."PollingSessionId"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."DustData"."PollingSessionId" IS 'Γò¿├¡Γòñ├╝Γòñ├»Γò¿ΓòùΓò¿ΓòæΓò¿Γûæ Γò¿Γò£Γò¿Γûæ Γòñ├╝Γò¿ΓòíΓòñ├╝Γòñ├╝Γò¿ΓòòΓòñ├ä Γò¿Γò¢Γò¿ΓöÉΓòñ├çΓò¿Γò¢Γòñ├╝Γò¿Γûæ, Γò¿Γûô Γòñ├çΓò¿ΓûæΓò¿Γò¥Γò¿ΓòæΓò¿ΓûæΓòñ├á Γò¿ΓòæΓò¿Γò¢Γòñ├⌐Γò¿Γò¢Γòñ├çΓò¿Γò¢Γò¿Γòú Γò¿ΓûÆΓòñ├»Γò¿ΓòùΓò¿Γòò Γò¿ΓöÉΓò¿Γò¢Γò¿ΓòùΓòñ├óΓòñ├ºΓò¿ΓòíΓò¿Γò£Γòñ├» Γòñ├¼Γòñ├⌐Γò¿Γòò Γò¿ΓöñΓò¿ΓûæΓò¿Γò£Γò¿Γò£Γòñ├»Γò¿Γòí';


--
-- Name: COLUMN "DustData"."MonitoringPostId"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."DustData"."MonitoringPostId" IS 'Γò¿├╢Γò¿ΓòíΓò¿Γò£Γò¿Γò¢Γòñ├çΓò¿Γò¥Γò¿ΓûæΓò¿ΓòùΓò¿ΓòòΓò¿ΓòûΓò¿Γò¢Γò¿ΓûôΓò¿ΓûæΓò¿Γò£Γò¿Γò£Γò¿Γò¢Γò¿Γòí Γò¿ΓöÉΓò¿Γò¢Γò¿ΓòùΓò¿Γòí ID Γò¿ΓöÉΓò¿Γò¢Γòñ├╝Γòñ├⌐Γò¿Γûæ Γò¿ΓöñΓò¿ΓòùΓòñ├à Γòñ├óΓòñ├╝Γò¿ΓòæΓò¿Γò¢Γòñ├çΓò¿ΓòíΓò¿Γò£Γò¿ΓòòΓòñ├à Γò¿ΓòûΓò¿ΓûæΓò¿ΓöÉΓòñ├çΓò¿Γò¢Γòñ├╝Γò¿Γò¢Γò¿Γûô';


--
-- Name: DustData_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."DustData_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."DustData_Id_seq" OWNER TO postgres;

--
-- Name: DustData_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."DustData_Id_seq" OWNED BY public."DustData"."Id";


--
-- Name: IWSData; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."IWSData" (
    "Id" integer NOT NULL,
    "SensorId" integer NOT NULL,
    "ReceivedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "DataTimestamp" timestamp with time zone NOT NULL,
    "EnvTemperature" numeric(5,2),
    "Humidity" numeric(5,2),
    "DewPoint" numeric(5,2),
    "PressureHPa" numeric(7,2),
    "PressureQNHHPa" numeric(7,2),
    "PressureMmHg" numeric(7,2),
    "WindSpeed" numeric(5,2),
    "WindDirection" numeric(6,2),
    "WindVSound" numeric(6,2),
    "PrecipitationType" integer,
    "PrecipitationIntensity" numeric(5,2),
    "PrecipitationQuantity" numeric(5,2),
    "PrecipitationElapsed" integer,
    "PrecipitationPeriod" integer,
    "CO2Level" numeric(6,2),
    "SupplyVoltage" numeric(5,1),
    "Latitude" numeric(10,6),
    "Longitude" numeric(10,6),
    "Altitude" numeric(7,2),
    "KSP" integer,
    "GPSSpeed" numeric(5,1),
    "AccelerationStDev" numeric(5,2),
    "Roll" numeric(5,1),
    "Pitch" numeric(5,1),
    "WeAreFine" integer,
    "PollingSessionId" uuid,
    "MonitoringPostId" integer
);


ALTER TABLE public."IWSData" OWNER TO postgres;

--
-- Name: COLUMN "IWSData"."PollingSessionId"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."IWSData"."PollingSessionId" IS 'Γò¿├¡Γòñ├╝Γòñ├»Γò¿ΓòùΓò¿ΓòæΓò¿Γûæ Γò¿Γò£Γò¿Γûæ Γòñ├╝Γò¿ΓòíΓòñ├╝Γòñ├╝Γò¿ΓòòΓòñ├ä Γò¿Γò¢Γò¿ΓöÉΓòñ├çΓò¿Γò¢Γòñ├╝Γò¿Γûæ, Γò¿Γûô Γòñ├çΓò¿ΓûæΓò¿Γò¥Γò¿ΓòæΓò¿ΓûæΓòñ├á Γò¿ΓòæΓò¿Γò¢Γòñ├⌐Γò¿Γò¢Γòñ├çΓò¿Γò¢Γò¿Γòú Γò¿ΓûÆΓòñ├»Γò¿ΓòùΓò¿Γòò Γò¿ΓöÉΓò¿Γò¢Γò¿ΓòùΓòñ├óΓòñ├ºΓò¿ΓòíΓò¿Γò£Γòñ├» Γòñ├¼Γòñ├⌐Γò¿Γòò Γò¿ΓöñΓò¿ΓûæΓò¿Γò£Γò¿Γò£Γòñ├»Γò¿Γòí';


--
-- Name: COLUMN "IWSData"."MonitoringPostId"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."IWSData"."MonitoringPostId" IS 'Γò¿├╢Γò¿ΓòíΓò¿Γò£Γò¿Γò¢Γòñ├çΓò¿Γò¥Γò¿ΓûæΓò¿ΓòùΓò¿ΓòòΓò¿ΓòûΓò¿Γò¢Γò¿ΓûôΓò¿ΓûæΓò¿Γò£Γò¿Γò£Γò¿Γò¢Γò¿Γòí Γò¿ΓöÉΓò¿Γò¢Γò¿ΓòùΓò¿Γòí ID Γò¿ΓöÉΓò¿Γò¢Γòñ├╝Γòñ├⌐Γò¿Γûæ Γò¿ΓöñΓò¿ΓòùΓòñ├à Γòñ├óΓòñ├╝Γò¿ΓòæΓò¿Γò¢Γòñ├çΓò¿ΓòíΓò¿Γò£Γò¿ΓòòΓòñ├à Γò¿ΓòûΓò¿ΓûæΓò¿ΓöÉΓòñ├çΓò¿Γò¢Γòñ├╝Γò¿Γò¢Γò¿Γûô';


--
-- Name: IWSData_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."IWSData_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."IWSData_Id_seq" OWNER TO postgres;

--
-- Name: IWSData_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."IWSData_Id_seq" OWNED BY public."IWSData"."Id";


--
-- Name: MUEKSData; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MUEKSData" (
    "Id" integer NOT NULL,
    "SensorId" integer NOT NULL,
    "ReceivedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "DataTimestamp" timestamp with time zone NOT NULL,
    "TemperatureBox" numeric(5,2),
    "UPowerIn12B" numeric(5,2),
    "UOut12B" numeric(5,2),
    "IOut12B" numeric(5,2),
    "IOut48B" numeric(5,2),
    "UAkb" numeric(5,2),
    "IAkb" numeric(5,2),
    "Sens220B" integer,
    "WhAkb" numeric(10,2),
    "VisibleRange" numeric(10,2),
    "DoorStatus" integer,
    "TdsH" character varying(50),
    "TdsTds" character varying(50),
    "TkosaT1" character varying(50),
    "TkosaT3" character varying(50),
    "PollingSessionId" uuid,
    "MonitoringPostId" integer
);


ALTER TABLE public."MUEKSData" OWNER TO postgres;

--
-- Name: COLUMN "MUEKSData"."PollingSessionId"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."MUEKSData"."PollingSessionId" IS 'Γò¿├¡Γòñ├╝Γòñ├»Γò¿ΓòùΓò¿ΓòæΓò¿Γûæ Γò¿Γò£Γò¿Γûæ Γòñ├╝Γò¿ΓòíΓòñ├╝Γòñ├╝Γò¿ΓòòΓòñ├ä Γò¿Γò¢Γò¿ΓöÉΓòñ├çΓò¿Γò¢Γòñ├╝Γò¿Γûæ, Γò¿Γûô Γòñ├çΓò¿ΓûæΓò¿Γò¥Γò¿ΓòæΓò¿ΓûæΓòñ├á Γò¿ΓòæΓò¿Γò¢Γòñ├⌐Γò¿Γò¢Γòñ├çΓò¿Γò¢Γò¿Γòú Γò¿ΓûÆΓòñ├»Γò¿ΓòùΓò¿Γòò Γò¿ΓöÉΓò¿Γò¢Γò¿ΓòùΓòñ├óΓòñ├ºΓò¿ΓòíΓò¿Γò£Γòñ├» Γòñ├¼Γòñ├⌐Γò¿Γòò Γò¿ΓöñΓò¿ΓûæΓò¿Γò£Γò¿Γò£Γòñ├»Γò¿Γòí';


--
-- Name: COLUMN "MUEKSData"."MonitoringPostId"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."MUEKSData"."MonitoringPostId" IS 'Γò¿├╢Γò¿ΓòíΓò¿Γò£Γò¿Γò¢Γòñ├çΓò¿Γò¥Γò¿ΓûæΓò¿ΓòùΓò¿ΓòòΓò¿ΓòûΓò¿Γò¢Γò¿ΓûôΓò¿ΓûæΓò¿Γò£Γò¿Γò£Γò¿Γò¢Γò¿Γòí Γò¿ΓöÉΓò¿Γò¢Γò¿ΓòùΓò¿Γòí ID Γò¿ΓöÉΓò¿Γò¢Γòñ├╝Γòñ├⌐Γò¿Γûæ Γò¿ΓöñΓò¿ΓòùΓòñ├à Γòñ├óΓòñ├╝Γò¿ΓòæΓò¿Γò¢Γòñ├çΓò¿ΓòíΓò¿Γò£Γò¿ΓòòΓòñ├à Γò¿ΓòûΓò¿ΓûæΓò¿ΓöÉΓòñ├çΓò¿Γò¢Γòñ├╝Γò¿Γò¢Γò¿Γûô';


--
-- Name: MUEKSData_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."MUEKSData_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."MUEKSData_Id_seq" OWNER TO postgres;

--
-- Name: MUEKSData_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."MUEKSData_Id_seq" OWNED BY public."MUEKSData"."Id";


--
-- Name: MonitoringPost; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."MonitoringPost" (
    "Id" integer NOT NULL,
    "Name" character varying(255) NOT NULL,
    "Description" text,
    "Longitude" double precision,
    "Latitude" double precision,
    "IsMobile" boolean DEFAULT false NOT NULL,
    "IsActive" boolean DEFAULT true NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "UpdatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "Address" text,
    "PollingIntervalSeconds" integer DEFAULT 60 NOT NULL,
    "LastPolledAt" timestamp without time zone,
    CONSTRAINT chk_monitoringpost_coordinates_valid CHECK (((("Longitude" IS NULL) AND ("Latitude" IS NULL)) OR (("Longitude" >= ('-180'::integer)::double precision) AND ("Longitude" <= (180)::double precision) AND (("Latitude" >= ('-90'::integer)::double precision) AND ("Latitude" <= (90)::double precision)))))
);


ALTER TABLE public."MonitoringPost" OWNER TO postgres;

--
-- Name: COLUMN "MonitoringPost"."PollingIntervalSeconds"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."MonitoringPost"."PollingIntervalSeconds" IS 'Γò¿├┐Γò¿Γò£Γòñ├⌐Γò¿ΓòíΓòñ├çΓò¿ΓûôΓò¿ΓûæΓò¿Γòù Γò¿Γò¢Γò¿ΓöÉΓòñ├çΓò¿Γò¢Γòñ├╝Γò¿Γûæ Γò¿ΓöñΓò¿ΓûæΓòñ├⌐Γòñ├ºΓò¿ΓòòΓò¿ΓòæΓò¿Γò¢Γò¿Γûô Γòñ├¼Γòñ├⌐Γò¿Γò¢Γò¿ΓöéΓò¿Γò¢ Γò¿ΓöÉΓò¿Γò¢Γòñ├╝Γòñ├⌐Γò¿Γûæ Γò¿Γûô Γòñ├╝Γò¿ΓòíΓò¿ΓòæΓòñ├óΓò¿Γò£Γò¿ΓöñΓò¿ΓûæΓòñ├á';


--
-- Name: COLUMN "MonitoringPost"."LastPolledAt"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."MonitoringPost"."LastPolledAt" IS 'Γò¿├åΓòñ├çΓò¿ΓòíΓò¿Γò¥Γòñ├à Γò¿ΓöÉΓò¿Γò¢Γòñ├╝Γò¿ΓòùΓò¿ΓòíΓò¿ΓöñΓò¿Γò£Γò¿ΓòíΓò¿ΓöéΓò¿Γò¢ Γòñ├óΓòñ├╝Γò¿ΓöÉΓò¿ΓòíΓòñ├¬Γò¿Γò£Γò¿Γò¢Γò¿ΓöéΓò¿Γò¢ Γò¿Γò¢Γò¿ΓöÉΓòñ├çΓò¿Γò¢Γòñ├╝Γò¿Γûæ Γò¿ΓûôΓòñ├╝Γò¿ΓòíΓòñ├á Γò¿ΓöñΓò¿ΓûæΓòñ├⌐Γòñ├ºΓò¿ΓòòΓò¿ΓòæΓò¿Γò¢Γò¿Γûô Γò¿ΓöÉΓò¿Γò¢Γòñ├╝Γòñ├⌐Γò¿Γûæ (UTC)';


--
-- Name: MonitoringPost_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."MonitoringPost_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."MonitoringPost_Id_seq" OWNER TO postgres;

--
-- Name: MonitoringPost_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."MonitoringPost_Id_seq" OWNED BY public."MonitoringPost"."Id";


--
-- Name: PollingSessions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PollingSessions" (
    "Id" uuid DEFAULT gen_random_uuid() NOT NULL,
    "MonitoringPostId" integer NOT NULL,
    "StartedAt" timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "CompletedAt" timestamp without time zone,
    "Status" character varying(20) DEFAULT 'IN_PROGRESS'::character varying NOT NULL,
    "TotalSensorsCount" integer DEFAULT 0 NOT NULL,
    "SuccessfulSensorsCount" integer DEFAULT 0 NOT NULL,
    "FailedSensorsDetails" jsonb,
    CONSTRAINT "CHK_PollingSessions_Status" CHECK ((("Status")::text = ANY (ARRAY[('IN_PROGRESS'::character varying)::text, ('COMPLETED'::character varying)::text, ('PARTIALLY_COMPLETED'::character varying)::text, ('FAILED'::character varying)::text])))
);


ALTER TABLE public."PollingSessions" OWNER TO postgres;

--
-- Name: TABLE "PollingSessions"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON TABLE public."PollingSessions" IS 'Γò¿├┤Γòñ├çΓòñ├óΓò¿ΓöÉΓò¿ΓöÉΓò¿ΓòòΓòñ├çΓòñ├óΓò¿ΓòíΓòñ├⌐ Γò¿Γò¢Γò¿ΓöÉΓòñ├çΓò¿Γò¢Γòñ├╝Γòñ├» Γò¿ΓöñΓò¿ΓûæΓòñ├⌐Γòñ├ºΓò¿ΓòòΓò¿ΓòæΓò¿Γò¢Γò¿Γûô Γò¿Γò¢Γò¿ΓöñΓò¿Γò£Γò¿Γò¢Γò¿ΓöéΓò¿Γò¢ Γò¿ΓöÉΓò¿Γò¢Γòñ├╝Γòñ├⌐Γò¿Γûæ Γò¿Γò¥Γò¿Γò¢Γò¿Γò£Γò¿ΓòòΓòñ├⌐Γò¿Γò¢Γòñ├çΓò¿ΓòòΓò¿Γò£Γò¿ΓöéΓò¿Γûæ Γò¿ΓöñΓò¿ΓòùΓòñ├à Γòñ├╝Γò¿ΓòòΓò¿Γò£Γòñ├áΓòñ├çΓò¿Γò¢Γò¿Γò£Γò¿ΓòòΓò¿ΓòûΓò¿ΓûæΓòñ├ÑΓò¿ΓòòΓò¿Γòò Γò¿ΓöñΓò¿ΓûæΓò¿Γò£Γò¿Γò£Γòñ├»Γòñ├á';


--
-- Name: COLUMN "PollingSessions"."Id"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."PollingSessions"."Id" IS 'Γò¿├║Γò¿Γò£Γò¿ΓòòΓò¿ΓòæΓò¿ΓûæΓò¿ΓòùΓòñ├«Γò¿Γò£Γòñ├»Γò¿Γòú Γò¿ΓòòΓò¿ΓöñΓò¿ΓòíΓò¿Γò£Γòñ├⌐Γò¿ΓòòΓòñ├ñΓò¿ΓòòΓò¿ΓòæΓò¿ΓûæΓòñ├⌐Γò¿Γò¢Γòñ├ç Γòñ├╝Γò¿ΓòíΓòñ├╝Γòñ├╝Γò¿ΓòòΓò¿Γòò Γò¿Γò¢Γò¿ΓöÉΓòñ├çΓò¿Γò¢Γòñ├╝Γò¿Γûæ';


--
-- Name: COLUMN "PollingSessions"."MonitoringPostId"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."PollingSessions"."MonitoringPostId" IS 'ID Γò¿ΓöÉΓò¿Γò¢Γòñ├╝Γòñ├⌐Γò¿Γûæ Γò¿Γò¥Γò¿Γò¢Γò¿Γò£Γò¿ΓòòΓòñ├⌐Γò¿Γò¢Γòñ├çΓò¿ΓòòΓò¿Γò£Γò¿ΓöéΓò¿Γûæ, Γò¿ΓöñΓò¿ΓûæΓòñ├⌐Γòñ├ºΓò¿ΓòòΓò¿ΓòæΓò¿Γòò Γò¿ΓòæΓò¿Γò¢Γòñ├⌐Γò¿Γò¢Γòñ├çΓò¿Γò¢Γò¿ΓöéΓò¿Γò¢ Γò¿Γò¢Γò¿ΓöÉΓòñ├çΓò¿ΓûæΓòñ├¬Γò¿ΓòòΓò¿ΓûôΓò¿ΓûæΓòñ├äΓòñ├⌐Γòñ├╝Γòñ├à';


--
-- Name: COLUMN "PollingSessions"."StartedAt"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."PollingSessions"."StartedAt" IS 'Γò¿├åΓòñ├çΓò¿ΓòíΓò¿Γò¥Γòñ├à Γò¿Γò£Γò¿ΓûæΓòñ├ºΓò¿ΓûæΓò¿ΓòùΓò¿Γûæ Γò¿Γò¢Γò¿ΓöÉΓòñ├çΓò¿Γò¢Γòñ├╝Γò¿Γûæ Γò¿ΓöéΓòñ├çΓòñ├óΓò¿ΓöÉΓò¿ΓöÉΓòñ├» Γò¿ΓöñΓò¿ΓûæΓòñ├⌐Γòñ├ºΓò¿ΓòòΓò¿ΓòæΓò¿Γò¢Γò¿Γûô (UTC)';


--
-- Name: COLUMN "PollingSessions"."CompletedAt"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."PollingSessions"."CompletedAt" IS 'Γò¿├åΓòñ├çΓò¿ΓòíΓò¿Γò¥Γòñ├à Γò¿ΓòûΓò¿ΓûæΓò¿ΓûôΓò¿ΓòíΓòñ├çΓòñ├¬Γò¿ΓòíΓò¿Γò£Γò¿ΓòòΓòñ├à Γò¿Γò¢Γò¿ΓöÉΓòñ├çΓò¿Γò¢Γòñ├╝Γò¿Γûæ Γò¿ΓûôΓòñ├╝Γò¿ΓòíΓòñ├á Γò¿ΓöñΓò¿ΓûæΓòñ├⌐Γòñ├ºΓò¿ΓòòΓò¿ΓòæΓò¿Γò¢Γò¿Γûô Γò¿ΓöéΓòñ├çΓòñ├óΓò¿ΓöÉΓò¿ΓöÉΓòñ├» (UTC)';


--
-- Name: COLUMN "PollingSessions"."Status"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."PollingSessions"."Status" IS 'Γò¿├¡Γòñ├⌐Γò¿ΓûæΓòñ├⌐Γòñ├óΓòñ├╝ Γòñ├╝Γò¿ΓòíΓòñ├╝Γòñ├╝Γò¿ΓòòΓò¿Γòò: IN_PROGRESS, COMPLETED (Γò¿ΓûôΓòñ├╝Γò¿Γòí Γòñ├óΓòñ├╝Γò¿ΓöÉΓò¿ΓòíΓòñ├¬Γò¿Γò£Γò¿Γò¢), PARTIALLY_COMPLETED (Γòñ├ºΓò¿ΓûæΓòñ├╝Γòñ├⌐Γò¿ΓòòΓòñ├ºΓò¿Γò£Γò¿Γò¢), FAILED (Γò¿Γò£Γò¿Γòò Γò¿Γò¢Γò¿ΓöñΓò¿ΓòòΓò¿Γò£ Γò¿ΓöñΓò¿ΓûæΓòñ├⌐Γòñ├ºΓò¿ΓòòΓò¿Γòæ Γò¿Γò£Γò¿Γòí Γò¿Γò¢Γòñ├⌐Γò¿ΓûôΓò¿ΓòíΓòñ├⌐Γò¿ΓòòΓò¿Γòù)';


--
-- Name: COLUMN "PollingSessions"."TotalSensorsCount"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."PollingSessions"."TotalSensorsCount" IS 'Γò¿ΓéºΓò¿ΓûÆΓòñ├½Γò¿ΓòíΓò¿Γòí Γò¿ΓòæΓò¿Γò¢Γò¿ΓòùΓò¿ΓòòΓòñ├ºΓò¿ΓòíΓòñ├╝Γòñ├⌐Γò¿ΓûôΓò¿Γò¢ Γò¿ΓöñΓò¿ΓûæΓòñ├⌐Γòñ├ºΓò¿ΓòòΓò¿ΓòæΓò¿Γò¢Γò¿Γûô, Γò¿ΓòæΓò¿Γò¢Γòñ├⌐Γò¿Γò¢Γòñ├çΓòñ├»Γò¿Γòí Γò¿ΓöÉΓò¿ΓòùΓò¿ΓûæΓò¿Γò£Γò¿ΓòòΓòñ├çΓò¿Γò¢Γò¿ΓûôΓò¿ΓûæΓò¿ΓòùΓò¿Γò¢Γòñ├╝Γòñ├« Γò¿Γò¢Γò¿ΓöÉΓòñ├çΓò¿Γò¢Γòñ├╝Γò¿ΓòòΓòñ├⌐Γòñ├« Γò¿Γûô Γòñ├¼Γòñ├⌐Γò¿Γò¢Γò¿Γòú Γòñ├╝Γò¿ΓòíΓòñ├╝Γòñ├╝Γò¿ΓòòΓò¿Γòò';


--
-- Name: COLUMN "PollingSessions"."SuccessfulSensorsCount"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."PollingSessions"."SuccessfulSensorsCount" IS 'Γò¿├£Γò¿Γò¢Γò¿ΓòùΓò¿ΓòòΓòñ├ºΓò¿ΓòíΓòñ├╝Γòñ├⌐Γò¿ΓûôΓò¿Γò¢ Γò¿ΓöñΓò¿ΓûæΓòñ├⌐Γòñ├ºΓò¿ΓòòΓò¿ΓòæΓò¿Γò¢Γò¿Γûô, Γòñ├óΓòñ├╝Γò¿ΓöÉΓò¿ΓòíΓòñ├¬Γò¿Γò£Γò¿Γò¢ Γò¿Γò¢Γò¿ΓöÉΓòñ├çΓò¿Γò¢Γòñ├¬Γò¿ΓòíΓò¿Γò£Γò¿Γò£Γòñ├»Γòñ├á Γò¿Γûô Γòñ├¼Γòñ├⌐Γò¿Γò¢Γò¿Γòú Γòñ├╝Γò¿ΓòíΓòñ├╝Γòñ├╝Γò¿ΓòòΓò¿Γòò';


--
-- Name: COLUMN "PollingSessions"."FailedSensorsDetails"; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public."PollingSessions"."FailedSensorsDetails" IS 'JSON Γòñ├╝ Γò¿ΓöñΓò¿ΓòíΓòñ├⌐Γò¿ΓûæΓò¿ΓòùΓòñ├àΓò¿Γò¥Γò¿Γòò Γò¿Γò¢Γòñ├¬Γò¿ΓòòΓò¿ΓûÆΓò¿Γò¢Γò¿Γòæ Γò¿ΓöÉΓò¿Γò¢ Γò¿ΓöñΓò¿ΓûæΓòñ├⌐Γòñ├ºΓò¿ΓòòΓò¿ΓòæΓò¿ΓûæΓò¿Γò¥, Γò¿ΓòæΓò¿Γò¢Γòñ├⌐Γò¿Γò¢Γòñ├çΓòñ├»Γò¿Γòí Γò¿Γò£Γò¿Γòí Γòñ├óΓò¿ΓöñΓò¿ΓûæΓò¿ΓòùΓò¿Γò¢Γòñ├╝Γòñ├« Γò¿Γò¢Γò¿ΓöÉΓòñ├çΓò¿Γò¢Γòñ├╝Γò¿ΓòòΓòñ├⌐Γòñ├«. Γò¿╞ÆΓòñ├çΓò¿ΓòòΓò¿Γò¥Γò¿ΓòíΓòñ├ç: {"failed_sensor_ids": [101,103], "errors": {"101":"Timeout", "103":"HTTP 500"}}';


--
-- Name: Puid; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Puid" (
    "Id" integer NOT NULL,
    "SensorType" character varying(64) DEFAULT 'PUID'::character varying NOT NULL,
    "MonitoringPostId" integer,
    "Longitude" double precision,
    "Latitude" double precision,
    "SerialNumber" character varying(64) NOT NULL,
    "EndPointsName" character varying(255) NOT NULL,
    "IntervalSeconds" integer DEFAULT 60 NOT NULL,
    "Url" text NOT NULL,
    "LastActivityUTC" timestamp with time zone,
    "CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "IsActive" boolean DEFAULT true NOT NULL
);


ALTER TABLE public."Puid" OWNER TO postgres;

--
-- Name: PuidData; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PuidData" (
    "Id" integer NOT NULL,
    "PuidId" integer NOT NULL,
    "MessageId" uuid NOT NULL,
    "SensorId" uuid NOT NULL,
    "SensorName" text,
    "Direction" integer,
    "Lane" integer NOT NULL,
    "Volume" integer,
    "Class0" integer,
    "Class1" integer,
    "Class2" integer,
    "Class3" integer,
    "Class4" integer,
    "Class5" integer,
    "GapAvg" double precision,
    "GapSum" double precision,
    "SpeedAvg" double precision,
    "HeadwayAvg" double precision,
    "HeadwaySum" double precision,
    "Speed85Avg" double precision,
    "OccupancyPer" text,
    "OccupancyPrc" double precision,
    "OccupancySum" double precision,
    "RangeStart" timestamp with time zone,
    "RangeEnd" timestamp with time zone,
    "RangeValue" integer,
    "CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);


ALTER TABLE public."PuidData" OWNER TO postgres;

--
-- Name: PuidData_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."PuidData_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."PuidData_Id_seq" OWNER TO postgres;

--
-- Name: PuidData_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."PuidData_Id_seq" OWNED BY public."PuidData"."Id";


--
-- Name: PuidResults; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."PuidResults" (
    "Id" integer NOT NULL,
    "PuidId" integer NOT NULL,
    "CheckedAt" timestamp with time zone NOT NULL,
    "StatusCode" integer NOT NULL,
    "ResponseBody" jsonb,
    "ResponseTimeMs" bigint NOT NULL,
    "IsSuccess" boolean NOT NULL
);


ALTER TABLE public."PuidResults" OWNER TO postgres;

--
-- Name: PuidResults_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."PuidResults_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."PuidResults_Id_seq" OWNER TO postgres;

--
-- Name: PuidResults_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."PuidResults_Id_seq" OWNED BY public."PuidResults"."Id";


--
-- Name: Puid_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."Puid_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."Puid_Id_seq" OWNER TO postgres;

--
-- Name: Puid_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."Puid_Id_seq" OWNED BY public."Puid"."Id";


--
-- Name: Sensor; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Sensor" (
    "Id" integer NOT NULL,
    "SensorTypeId" integer NOT NULL,
    "MonitoringPostId" integer,
    "Longitude" double precision,
    "Latitude" double precision,
    "SerialNumber" character varying(64) NOT NULL,
    "EndPointsName" character varying(255) NOT NULL,
    "Url" text NOT NULL,
    "LastActivityUTC" timestamp with time zone,
    "CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "IsActive" boolean DEFAULT true NOT NULL,
    CONSTRAINT chk_sensor_coordinates_valid CHECK (((("Longitude" IS NULL) AND ("Latitude" IS NULL)) OR (("Longitude" >= ('-180'::integer)::double precision) AND ("Longitude" <= (180)::double precision) AND (("Latitude" >= ('-90'::integer)::double precision) AND ("Latitude" <= (90)::double precision)))))
);


ALTER TABLE public."Sensor" OWNER TO postgres;

--
-- Name: SensorError; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SensorError" (
    "Id" integer NOT NULL,
    "SensorId" integer NOT NULL,
    "ErrorLevel" character varying(20) NOT NULL,
    "ErrorMessage" text NOT NULL,
    "StackTrace" text,
    "ErrorSource" character varying(255),
    "ExceptionType" character varying(255),
    "CreatedAt" timestamp with time zone DEFAULT now() NOT NULL,
    "AdditionalData" jsonb
);


ALTER TABLE public."SensorError" OWNER TO postgres;

--
-- Name: SensorError_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."SensorError_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."SensorError_Id_seq" OWNER TO postgres;

--
-- Name: SensorError_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."SensorError_Id_seq" OWNED BY public."SensorError"."Id";


--
-- Name: SensorResults; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SensorResults" (
    "Id" integer NOT NULL,
    "SensorId" integer NOT NULL,
    "CheckedAt" timestamp with time zone NOT NULL,
    "StatusCode" integer NOT NULL,
    "ResponseBody" jsonb,
    "ResponseTimeMs" bigint NOT NULL,
    "IsSuccess" boolean NOT NULL,
    "PollingSessionId" uuid
);


ALTER TABLE public."SensorResults" OWNER TO postgres;

--
-- Name: SensorResults_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."SensorResults_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."SensorResults_Id_seq" OWNER TO postgres;

--
-- Name: SensorResults_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."SensorResults_Id_seq" OWNED BY public."SensorResults"."Id";


--
-- Name: SensorType; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."SensorType" (
    "Id" integer NOT NULL,
    "SensorTypeName" character varying(20) NOT NULL,
    "Description" text NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT now() NOT NULL
);


ALTER TABLE public."SensorType" OWNER TO postgres;

--
-- Name: SensorType_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."SensorType_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."SensorType_Id_seq" OWNER TO postgres;

--
-- Name: SensorType_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."SensorType_Id_seq" OWNED BY public."SensorType"."Id";


--
-- Name: Sensor_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."Sensor_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."Sensor_Id_seq" OWNER TO postgres;

--
-- Name: Sensor_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."Sensor_Id_seq" OWNED BY public."Sensor"."Id";


--
-- Name: Snapshots; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Snapshots" (
    "Id" integer NOT NULL,
    "CameraId" integer NOT NULL,
    "FilePath" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL
);


ALTER TABLE public."Snapshots" OWNER TO postgres;

--
-- Name: Snapshots_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Snapshots" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Snapshots_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "UserName" character varying(100) NOT NULL,
    "PasswordHash" text NOT NULL,
    "Salt" text NOT NULL,
    "Role" character varying(50) NOT NULL,
    "CreatedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: WebParts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."WebParts" (
    id integer NOT NULL,
    title character varying(200) DEFAULT ''::character varying NOT NULL,
    type integer DEFAULT 0 NOT NULL,
    position_x integer DEFAULT 0 NOT NULL,
    position_y integer DEFAULT 0 NOT NULL,
    width integer DEFAULT 6 NOT NULL,
    height integer DEFAULT 4 NOT NULL,
    settings text DEFAULT '{}'::text NOT NULL,
    data text DEFAULT '{}'::text NOT NULL,
    user_id integer DEFAULT 0 NOT NULL
);


ALTER TABLE public."WebParts" OWNER TO postgres;

--
-- Name: WebParts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."WebParts_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."WebParts_id_seq" OWNER TO postgres;

--
-- Name: WebParts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."WebParts_id_seq" OWNED BY public."WebParts".id;


--
-- Name: WorkerConfiguration; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."WorkerConfiguration" (
    "Id" integer NOT NULL,
    "Key" character varying(100) NOT NULL,
    "Value" text NOT NULL,
    "DataType" character varying(50) NOT NULL,
    "Description" text,
    "LastModified" timestamp with time zone DEFAULT now() NOT NULL,
    "ModifiedBy" character varying(100),
    "IsActive" boolean DEFAULT true NOT NULL,
    CONSTRAINT "WorkerConfiguration_DataType_check" CHECK ((("DataType")::text = ANY (ARRAY[('boolean'::character varying)::text, ('integer'::character varying)::text, ('string'::character varying)::text, ('decimal'::character varying)::text, ('json'::character varying)::text])))
);


ALTER TABLE public."WorkerConfiguration" OWNER TO postgres;

--
-- Name: WorkerConfiguration_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public."WorkerConfiguration_Id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public."WorkerConfiguration_Id_seq" OWNER TO postgres;

--
-- Name: WorkerConfiguration_Id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public."WorkerConfiguration_Id_seq" OWNED BY public."WorkerConfiguration"."Id";


--
-- Name: vw_dov_data_full; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_dov_data_full AS
 SELECT dd."Id" AS dov_data_id,
    dd."ReceivedAt" AS received_at,
    dd."DataTimestamp" AS data_timestamp,
    dd."VisibleRange" AS visible_range,
    dd."BrightFlag" AS bright_flag,
    s."Id" AS sensor_id,
    s."Longitude" AS sensor_longitude,
    s."Latitude" AS sensor_latitude,
    s."SerialNumber" AS serial_number,
    s."EndPointsName" AS endpoint_name,
    s."Url" AS sensor_url,
    s."LastActivityUTC" AS last_activity_utc,
    s."IsActive" AS sensor_is_active,
    st."Id" AS sensor_type_id,
    st."SensorTypeName" AS sensor_type_name,
    st."Description" AS sensor_type_description,
    mp."Id" AS post_id,
    mp."Name" AS post_name,
    mp."Address" AS post_address,
    mp."Description" AS post_description,
    mp."IsMobile" AS post_is_mobile,
    mp."IsActive" AS post_is_active
   FROM (((public."DOVData" dd
     LEFT JOIN public."Sensor" s ON ((dd."SensorId" = s."Id")))
     LEFT JOIN public."SensorType" st ON ((s."SensorTypeId" = st."Id")))
     LEFT JOIN public."MonitoringPost" mp ON ((s."MonitoringPostId" = mp."Id")));


ALTER VIEW public.vw_dov_data_full OWNER TO postgres;

--
-- Name: vw_dspd_data_full; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_dspd_data_full AS
 SELECT dd."Id" AS dspd_data_id,
    dd."ReceivedAt" AS received_at,
    dd."DataTimestamp" AS data_timestamp,
    dd."Grip" AS grip_coefficient,
    dd."Shake" AS shake_level,
    dd."UPower" AS voltage_power,
    dd."TemperatureCase" AS case_temperature,
    dd."TemperatureRoad" AS road_temperature,
    dd."HeightH2O" AS water_height,
    dd."HeightIce" AS ice_height,
    dd."HeightSnow" AS snow_height,
    dd."PercentICE" AS ice_percentage,
    dd."PercentPGM" AS pgm_percentage,
    dd."RoadStatus" AS road_status_code,
    dd."AngleToRoad" AS road_angle,
    dd."TemperatureFreezePGM" AS freeze_temperature,
    dd."NeedCalibration" AS calibration_needed,
    dd."GPSLatitude" AS gps_latitude,
    dd."GPSLongitude" AS gps_longitude,
    dd."IsGpsValid" AS gps_valid,
    dd."DistanceToSurface" AS distance_to_surface,
    s."Id" AS sensor_id,
    s."Longitude" AS sensor_longitude,
    s."Latitude" AS sensor_latitude,
    s."SerialNumber" AS serial_number,
    s."EndPointsName" AS endpoint_name,
    s."Url" AS sensor_url,
    s."LastActivityUTC" AS last_activity_utc,
    s."IsActive" AS sensor_is_active,
    st."Id" AS sensor_type_id,
    st."SensorTypeName" AS sensor_type_name,
    st."Description" AS sensor_type_description,
    mp."Id" AS post_id,
    mp."Name" AS post_name,
    mp."Address" AS post_address,
    mp."Description" AS post_description,
    mp."IsMobile" AS post_is_mobile,
    mp."IsActive" AS post_is_active
   FROM (((public."DSPDData" dd
     LEFT JOIN public."Sensor" s ON ((dd."SensorId" = s."Id")))
     LEFT JOIN public."SensorType" st ON ((s."SensorTypeId" = st."Id")))
     LEFT JOIN public."MonitoringPost" mp ON ((s."MonitoringPostId" = mp."Id")));


ALTER VIEW public.vw_dspd_data_full OWNER TO postgres;

--
-- Name: vw_dust_data_full; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_dust_data_full AS
 SELECT dd."Id" AS dust_data_id,
    dd."ReceivedAt" AS received_at,
    dd."DataTimestamp" AS data_timestamp,
    dd."PM10Act" AS pm10act,
    dd."PM25Act" AS pm25act,
    dd."PM1Act" AS pm1act,
    dd."PM10AWG" AS pm10awg,
    dd."PM25AWG" AS pm25awg,
    dd."PM1AWG" AS pm1awg,
    dd."FlowProbe" AS flowprobe,
    dd."TemperatureProbe" AS temperatureprobe,
    dd."HumidityProbe" AS humidityprobe,
    dd."LaserStatus" AS laserstatus,
    dd."SupplyVoltage" AS supplyvoltage,
    s."Id" AS sensor_id,
    s."Longitude" AS sensor_longitude,
    s."Latitude" AS sensor_latitude,
    s."SerialNumber" AS serial_number,
    s."EndPointsName" AS endpoint_name,
    s."Url" AS sensor_url,
    s."LastActivityUTC" AS last_activity_utc,
    s."IsActive" AS sensor_is_active,
    st."Id" AS sensor_type_id,
    st."SensorTypeName" AS sensor_type_name,
    st."Description" AS sensor_type_description,
    mp."Id" AS post_id,
    mp."Name" AS post_name,
    mp."Address" AS post_address,
    mp."Description" AS post_description,
    mp."IsMobile" AS post_is_mobile,
    mp."IsActive" AS post_is_active
   FROM (((public."DustData" dd
     LEFT JOIN public."Sensor" s ON ((dd."SensorId" = s."Id")))
     LEFT JOIN public."SensorType" st ON ((s."SensorTypeId" = st."Id")))
     LEFT JOIN public."MonitoringPost" mp ON ((s."MonitoringPostId" = mp."Id")));


ALTER VIEW public.vw_dust_data_full OWNER TO postgres;

--
-- Name: vw_iws_data_full; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_iws_data_full AS
 SELECT iws."Id" AS iws_data_id,
    iws."ReceivedAt" AS received_at,
    iws."DataTimestamp" AS data_timestamp,
    iws."EnvTemperature" AS environment_temperature,
    iws."Humidity" AS humidity_percentage,
    iws."DewPoint" AS dew_point,
    iws."PressureHPa" AS pressure_hpa,
    iws."PressureQNHHPa" AS pressure_qnh_hpa,
    iws."PressureMmHg" AS pressure_mmhg,
    iws."WindSpeed" AS wind_speed,
    iws."WindDirection" AS wind_direction,
    iws."WindVSound" AS wind_vs_sound,
    iws."PrecipitationType" AS precipitation_type,
    iws."PrecipitationIntensity" AS precipitation_intensity,
    iws."PrecipitationQuantity" AS precipitation_quantity,
    iws."PrecipitationElapsed" AS precipitation_elapsed,
    iws."PrecipitationPeriod" AS precipitation_period,
    iws."CO2Level" AS co2_level,
    iws."SupplyVoltage" AS supply_voltage,
    iws."Latitude" AS iws_latitude,
    iws."Longitude" AS iws_longitude,
    iws."Altitude" AS altitude,
    iws."KSP" AS ksp_value,
    iws."GPSSpeed" AS gps_speed,
    iws."AccelerationStDev" AS acceleration_std_dev,
    iws."Roll" AS roll_angle,
    iws."Pitch" AS pitch_angle,
    iws."WeAreFine" AS status_ok,
    s."Id" AS sensor_id,
    s."Longitude" AS sensor_longitude,
    s."Latitude" AS sensor_latitude,
    s."SerialNumber" AS serial_number,
    s."EndPointsName" AS endpoint_name,
    s."Url" AS sensor_url,
    s."LastActivityUTC" AS last_activity_utc,
    s."IsActive" AS sensor_is_active,
    st."Id" AS sensor_type_id,
    st."SensorTypeName" AS sensor_type_name,
    st."Description" AS sensor_type_description,
    mp."Id" AS post_id,
    mp."Name" AS post_name,
    mp."Address" AS post_address,
    mp."Description" AS post_description,
    mp."IsMobile" AS post_is_mobile,
    mp."IsActive" AS post_is_active
   FROM (((public."IWSData" iws
     LEFT JOIN public."Sensor" s ON ((iws."SensorId" = s."Id")))
     LEFT JOIN public."SensorType" st ON ((s."SensorTypeId" = st."Id")))
     LEFT JOIN public."MonitoringPost" mp ON ((s."MonitoringPostId" = mp."Id")));


ALTER VIEW public.vw_iws_data_full OWNER TO postgres;

--
-- Name: vw_meteo_standart_last; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_meteo_standart_last AS
 SELECT ps."Id" AS "PollingSessionId",
    ps."MonitoringPostId",
    ps."StartedAt",
    ps."CompletedAt",
    ps."Status",
    dov."VisibleRange",
    iws."EnvTemperature",
    iws."Humidity",
    iws."DewPoint",
    iws."PressureHPa",
    iws."PressureQNHHPa",
    iws."PressureMmHg",
    iws."WindSpeed",
    iws."WindDirection",
    iws."WindVSound",
    iws."PrecipitationType",
    iws."PrecipitationIntensity",
    iws."PrecipitationQuantity",
    iws."PrecipitationElapsed",
    iws."PrecipitationPeriod",
    dspd."Grip",
    dspd."Shake",
    dspd."UPower",
    dspd."TemperatureCase",
    dspd."TemperatureRoad",
    dspd."HeightH2O",
    dspd."HeightIce",
    dspd."HeightSnow",
    dspd."PercentICE",
    dspd."PercentPGM",
    dspd."RoadStatus",
    dspd."AngleToRoad",
    dspd."TemperatureFreezePGM"
   FROM (((public."PollingSessions" ps
     LEFT JOIN public."DOVData" dov ON ((ps."Id" = dov."PollingSessionId")))
     LEFT JOIN public."IWSData" iws ON ((ps."Id" = iws."PollingSessionId")))
     LEFT JOIN public."DSPDData" dspd ON ((ps."Id" = dspd."PollingSessionId")))
  WHERE (ps."Id" = ( SELECT "PollingSessions"."Id"
           FROM public."PollingSessions"
          WHERE (("PollingSessions"."Status")::text <> 'IN_PROGRESS'::text)
          ORDER BY "PollingSessions"."CompletedAt" DESC
         LIMIT 1))
  ORDER BY dov."Id", iws."Id", dspd."Id";


ALTER VIEW public.vw_meteo_standart_last OWNER TO postgres;

--
-- Name: vw_mueks_data_full; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_mueks_data_full AS
 SELECT pd."Id" AS mueks_data_id,
    pd."ReceivedAt" AS received_at,
    pd."DataTimestamp" AS data_timestamp,
    pd."TemperatureBox" AS temperature_box,
    pd."UPowerIn12B" AS voltage_power_in_12b,
    pd."UOut12B" AS voltage_out_12b,
    pd."IOut12B" AS current_out_12b,
    pd."IOut48B" AS current_out_48b,
    pd."UAkb" AS voltage_akb,
    pd."IAkb" AS current_akb,
    pd."Sens220B" AS sensor_220b,
    pd."WhAkb" AS watt_hours_akb,
    pd."VisibleRange" AS visible_range,
    pd."DoorStatus" AS door_status,
    pd."TdsH" AS tds_h,
    pd."TdsTds" AS tds_tds,
    pd."TkosaT1" AS tkosa_t1,
    pd."TkosaT3" AS tkosa_t3,
    s."Id" AS sensor_id,
    s."Longitude" AS sensor_longitude,
    s."Latitude" AS sensor_latitude,
    s."SerialNumber" AS serial_number,
    s."EndPointsName" AS endpoint_name,
    s."Url" AS sensor_url,
    s."LastActivityUTC" AS last_activity_utc,
    s."IsActive" AS sensor_is_active,
    st."Id" AS sensor_type_id,
    st."SensorTypeName" AS sensor_type_name,
    st."Description" AS sensor_type_description,
    mp."Id" AS post_id,
    mp."Name" AS post_name,
    mp."Address" AS post_address,
    mp."Description" AS post_description,
    mp."IsMobile" AS post_is_mobile,
    mp."IsActive" AS post_is_active
   FROM (((public."MUEKSData" pd
     LEFT JOIN public."Sensor" s ON ((pd."SensorId" = s."Id")))
     LEFT JOIN public."SensorType" st ON ((s."SensorTypeId" = st."Id")))
     LEFT JOIN public."MonitoringPost" mp ON ((s."MonitoringPostId" = mp."Id")));


ALTER VIEW public.vw_mueks_data_full OWNER TO postgres;

--
-- Name: vw_sensor_errors_full; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_sensor_errors_full AS
 SELECT se."Id" AS error_id,
    se."ErrorLevel" AS error_level,
    se."ErrorMessage" AS error_message,
    se."StackTrace" AS stack_trace,
    se."ErrorSource" AS error_source,
    se."ExceptionType" AS exception_type,
    se."CreatedAt" AS error_created_at,
    se."AdditionalData" AS additional_data,
    s."Id" AS sensor_id,
    s."Longitude" AS sensor_longitude,
    s."Latitude" AS sensor_latitude,
    s."SerialNumber" AS serial_number,
    s."EndPointsName" AS endpoint_name,
    s."Url" AS sensor_url,
    s."LastActivityUTC" AS last_activity_utc,
    s."IsActive" AS sensor_is_active,
    st."Id" AS sensor_type_id,
    st."SensorTypeName" AS sensor_type_name,
    st."Description" AS sensor_type_description,
    mp."Id" AS post_id,
    mp."Name" AS post_name,
    mp."Address" AS post_address,
    mp."Description" AS post_description,
    mp."Longitude" AS post_longitude,
    mp."Latitude" AS post_latitude,
    mp."IsMobile" AS post_is_mobile,
    mp."IsActive" AS post_is_active,
    mp."UpdatedAt" AS post_updated_at
   FROM (((public."SensorError" se
     LEFT JOIN public."Sensor" s ON ((se."SensorId" = s."Id")))
     LEFT JOIN public."SensorType" st ON ((s."SensorTypeId" = st."Id")))
     LEFT JOIN public."MonitoringPost" mp ON ((s."MonitoringPostId" = mp."Id")));


ALTER VIEW public.vw_sensor_errors_full OWNER TO postgres;

--
-- Name: vw_sensor_results_full; Type: VIEW; Schema: public; Owner: postgres
--

CREATE VIEW public.vw_sensor_results_full AS
 SELECT sr."Id" AS result_id,
    sr."CheckedAt" AS checked_at,
    sr."StatusCode" AS status_code,
    sr."ResponseBody" AS response_body,
    sr."ResponseTimeMs" AS response_time_ms,
    sr."IsSuccess" AS is_success,
    s."Id" AS sensor_id,
    s."Longitude" AS sensor_longitude,
    s."Latitude" AS sensor_latitude,
    s."SerialNumber" AS serial_number,
    s."EndPointsName" AS endpoint_name,
    s."Url" AS sensor_url,
    s."LastActivityUTC" AS last_activity_utc,
    s."IsActive" AS sensor_is_active,
    st."Id" AS sensor_type_id,
    st."SensorTypeName" AS sensor_type_name,
    st."Description" AS sensor_type_description,
    mp."Id" AS post_id,
    mp."Name" AS post_name,
    mp."Address" AS post_address,
    mp."Description" AS post_description,
    mp."IsMobile" AS post_is_mobile,
    mp."IsActive" AS post_is_active
   FROM (((public."SensorResults" sr
     LEFT JOIN public."Sensor" s ON ((sr."SensorId" = s."Id")))
     LEFT JOIN public."SensorType" st ON ((s."SensorTypeId" = st."Id")))
     LEFT JOIN public."MonitoringPost" mp ON ((s."MonitoringPostId" = mp."Id")));


ALTER VIEW public.vw_sensor_results_full OWNER TO postgres;

--
-- Name: DOVData Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DOVData" ALTER COLUMN "Id" SET DEFAULT nextval('public."DOVData_Id_seq"'::regclass);


--
-- Name: DSPDData Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DSPDData" ALTER COLUMN "Id" SET DEFAULT nextval('public."DSPDData_Id_seq"'::regclass);


--
-- Name: DustData Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DustData" ALTER COLUMN "Id" SET DEFAULT nextval('public."DustData_Id_seq"'::regclass);


--
-- Name: IWSData Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."IWSData" ALTER COLUMN "Id" SET DEFAULT nextval('public."IWSData_Id_seq"'::regclass);


--
-- Name: MUEKSData Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MUEKSData" ALTER COLUMN "Id" SET DEFAULT nextval('public."MUEKSData_Id_seq"'::regclass);


--
-- Name: MonitoringPost Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MonitoringPost" ALTER COLUMN "Id" SET DEFAULT nextval('public."MonitoringPost_Id_seq"'::regclass);


--
-- Name: Puid Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Puid" ALTER COLUMN "Id" SET DEFAULT nextval('public."Puid_Id_seq"'::regclass);


--
-- Name: PuidData Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PuidData" ALTER COLUMN "Id" SET DEFAULT nextval('public."PuidData_Id_seq"'::regclass);


--
-- Name: PuidResults Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PuidResults" ALTER COLUMN "Id" SET DEFAULT nextval('public."PuidResults_Id_seq"'::regclass);


--
-- Name: Sensor Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sensor" ALTER COLUMN "Id" SET DEFAULT nextval('public."Sensor_Id_seq"'::regclass);


--
-- Name: SensorError Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SensorError" ALTER COLUMN "Id" SET DEFAULT nextval('public."SensorError_Id_seq"'::regclass);


--
-- Name: SensorResults Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SensorResults" ALTER COLUMN "Id" SET DEFAULT nextval('public."SensorResults_Id_seq"'::regclass);


--
-- Name: SensorType Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SensorType" ALTER COLUMN "Id" SET DEFAULT nextval('public."SensorType_Id_seq"'::regclass);


--
-- Name: WebParts id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WebParts" ALTER COLUMN id SET DEFAULT nextval('public."WebParts_id_seq"'::regclass);


--
-- Name: WorkerConfiguration Id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WorkerConfiguration" ALTER COLUMN "Id" SET DEFAULT nextval('public."WorkerConfiguration_Id_seq"'::regclass);


--
-- Name: DOVData DOVData_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DOVData"
    ADD CONSTRAINT "DOVData_pkey" PRIMARY KEY ("Id");


--
-- Name: DSPDData DSPDData_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DSPDData"
    ADD CONSTRAINT "DSPDData_pkey" PRIMARY KEY ("Id");


--
-- Name: DustData DustData_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DustData"
    ADD CONSTRAINT "DustData_pkey" PRIMARY KEY ("Id");


--
-- Name: IWSData IWSData_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."IWSData"
    ADD CONSTRAINT "IWSData_pkey" PRIMARY KEY ("Id");


--
-- Name: MUEKSData MUEKSData_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MUEKSData"
    ADD CONSTRAINT "MUEKSData_pkey" PRIMARY KEY ("Id");


--
-- Name: MonitoringPost MonitoringPost_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MonitoringPost"
    ADD CONSTRAINT "MonitoringPost_pkey" PRIMARY KEY ("Id");


--
-- Name: AuditLogs PK_AuditLogs; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AuditLogs"
    ADD CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id");


--
-- Name: Cameras PK_Cameras; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Cameras"
    ADD CONSTRAINT "PK_Cameras" PRIMARY KEY ("Id");


--
-- Name: Snapshots PK_Snapshots; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Snapshots"
    ADD CONSTRAINT "PK_Snapshots" PRIMARY KEY ("Id");


--
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- Name: PollingSessions PollingSessions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PollingSessions"
    ADD CONSTRAINT "PollingSessions_pkey" PRIMARY KEY ("Id");


--
-- Name: PuidData PuidData_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PuidData"
    ADD CONSTRAINT "PuidData_pkey" PRIMARY KEY ("Id");


--
-- Name: PuidResults PuidResults_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PuidResults"
    ADD CONSTRAINT "PuidResults_pkey" PRIMARY KEY ("Id");


--
-- Name: Puid Puid_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Puid"
    ADD CONSTRAINT "Puid_pkey" PRIMARY KEY ("Id");


--
-- Name: SensorError SensorError_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SensorError"
    ADD CONSTRAINT "SensorError_pkey" PRIMARY KEY ("Id");


--
-- Name: SensorResults SensorResults_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SensorResults"
    ADD CONSTRAINT "SensorResults_pkey" PRIMARY KEY ("Id");


--
-- Name: SensorType SensorType_SensorTypeName_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SensorType"
    ADD CONSTRAINT "SensorType_SensorTypeName_key" UNIQUE ("SensorTypeName");


--
-- Name: SensorType SensorType_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SensorType"
    ADD CONSTRAINT "SensorType_pkey" PRIMARY KEY ("Id");


--
-- Name: Sensor Sensor_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sensor"
    ADD CONSTRAINT "Sensor_pkey" PRIMARY KEY ("Id");


--
-- Name: WebParts WebParts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WebParts"
    ADD CONSTRAINT "WebParts_pkey" PRIMARY KEY (id);


--
-- Name: WorkerConfiguration WorkerConfiguration_Key_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WorkerConfiguration"
    ADD CONSTRAINT "WorkerConfiguration_Key_key" UNIQUE ("Key");


--
-- Name: WorkerConfiguration WorkerConfiguration_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."WorkerConfiguration"
    ADD CONSTRAINT "WorkerConfiguration_pkey" PRIMARY KEY ("Id");


--
-- Name: IX_AuditLogs_Action; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AuditLogs_Action" ON public."AuditLogs" USING btree ("Action");


--
-- Name: IX_AuditLogs_ChangeType; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AuditLogs_ChangeType" ON public."AuditLogs" USING btree ("ChangeType");


--
-- Name: IX_AuditLogs_EntityId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AuditLogs_EntityId" ON public."AuditLogs" USING btree ("EntityId");


--
-- Name: IX_AuditLogs_EntityType; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AuditLogs_EntityType" ON public."AuditLogs" USING btree ("EntityType");


--
-- Name: IX_AuditLogs_Timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AuditLogs_Timestamp" ON public."AuditLogs" USING btree ("Timestamp");


--
-- Name: IX_AuditLogs_Type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AuditLogs_Type" ON public."AuditLogs" USING btree ("Type");


--
-- Name: IX_AuditLogs_UserId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AuditLogs_UserId" ON public."AuditLogs" USING btree ("UserId");


--
-- Name: IX_AuditLogs_UserName; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_AuditLogs_UserName" ON public."AuditLogs" USING btree ("UserName");


--
-- Name: IX_Cameras_MonitoringPostId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Cameras_MonitoringPostId" ON public."Cameras" USING btree ("MonitoringPostId");


--
-- Name: IX_DOVData_MonitoringPostId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_DOVData_MonitoringPostId" ON public."DOVData" USING btree ("MonitoringPostId");


--
-- Name: IX_DOVData_PollingSessionId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_DOVData_PollingSessionId" ON public."DOVData" USING btree ("PollingSessionId");


--
-- Name: IX_DSPDData_MonitoringPostId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_DSPDData_MonitoringPostId" ON public."DSPDData" USING btree ("MonitoringPostId");


--
-- Name: IX_DSPDData_PollingSessionId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_DSPDData_PollingSessionId" ON public."DSPDData" USING btree ("PollingSessionId");


--
-- Name: IX_DustData_MonitoringPostId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_DustData_MonitoringPostId" ON public."DustData" USING btree ("MonitoringPostId");


--
-- Name: IX_DustData_PollingSessionId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_DustData_PollingSessionId" ON public."DustData" USING btree ("PollingSessionId");


--
-- Name: IX_IWSData_MonitoringPostId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_IWSData_MonitoringPostId" ON public."IWSData" USING btree ("MonitoringPostId");


--
-- Name: IX_IWSData_PollingSessionId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_IWSData_PollingSessionId" ON public."IWSData" USING btree ("PollingSessionId");


--
-- Name: IX_MUEKSData_MonitoringPostId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MUEKSData_MonitoringPostId" ON public."MUEKSData" USING btree ("MonitoringPostId");


--
-- Name: IX_MUEKSData_PollingSessionId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MUEKSData_PollingSessionId" ON public."MUEKSData" USING btree ("PollingSessionId");


--
-- Name: IX_MonitoringPost_LastPolledAt_Interval; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_MonitoringPost_LastPolledAt_Interval" ON public."MonitoringPost" USING btree ("LastPolledAt", "PollingIntervalSeconds") WHERE ("IsActive" = true);


--
-- Name: IX_PollingSessions_MonitoringPostId_StartedAt; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PollingSessions_MonitoringPostId_StartedAt" ON public."PollingSessions" USING btree ("MonitoringPostId", "StartedAt" DESC);


--
-- Name: IX_PollingSessions_Status_StartedAt; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PollingSessions_Status_StartedAt" ON public."PollingSessions" USING btree ("Status", "StartedAt");


--
-- Name: IX_PollingSessions_Status_SuccessCount; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PollingSessions_Status_SuccessCount" ON public."PollingSessions" USING btree ("Status", "SuccessfulSensorsCount");


--
-- Name: IX_PuidData_PuidId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PuidData_PuidId" ON public."PuidData" USING btree ("PuidId");


--
-- Name: IX_PuidData_RangeStart; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_PuidData_RangeStart" ON public."PuidData" USING btree ("RangeStart");


--
-- Name: IX_Snapshots_CameraId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "IX_Snapshots_CameraId" ON public."Snapshots" USING btree ("CameraId");


--
-- Name: IX_Users_UserName; Type: INDEX; Schema: public; Owner: postgres
--

CREATE UNIQUE INDEX "IX_Users_UserName" ON public."Users" USING btree ("UserName");


--
-- Name: idx_DustData_DataTimestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "idx_DustData_DataTimestamp" ON public."DustData" USING btree ("DataTimestamp");


--
-- Name: idx_DustData_SensorId; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX "idx_DustData_SensorId" ON public."DustData" USING btree ("SensorId");


--
-- Name: idx_dovdata_sensor_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dovdata_sensor_timestamp ON public."DOVData" USING btree ("SensorId", "DataTimestamp");


--
-- Name: idx_dovdata_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dovdata_timestamp ON public."DOVData" USING btree ("DataTimestamp");


--
-- Name: idx_dovdata_visibility; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dovdata_visibility ON public."DOVData" USING btree ("VisibleRange");


--
-- Name: idx_dspddata_grip; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dspddata_grip ON public."DSPDData" USING btree ("Grip");


--
-- Name: idx_dspddata_roadstatus; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dspddata_roadstatus ON public."DSPDData" USING btree ("RoadStatus");


--
-- Name: idx_dspddata_sensor_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dspddata_sensor_timestamp ON public."DSPDData" USING btree ("SensorId", "DataTimestamp");


--
-- Name: idx_dspddata_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_dspddata_timestamp ON public."DSPDData" USING btree ("DataTimestamp");


--
-- Name: idx_iwsdata_sensor_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_iwsdata_sensor_timestamp ON public."IWSData" USING btree ("SensorId", "DataTimestamp");


--
-- Name: idx_iwsdata_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_iwsdata_timestamp ON public."IWSData" USING btree ("DataTimestamp");


--
-- Name: idx_iwsdata_weather; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_iwsdata_weather ON public."IWSData" USING btree ("EnvTemperature", "Humidity", "WindSpeed");


--
-- Name: idx_monitoringpost_active; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_monitoringpost_active ON public."MonitoringPost" USING btree ("IsActive");


--
-- Name: idx_monitoringpost_coordinates; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_monitoringpost_coordinates ON public."MonitoringPost" USING btree ("Longitude", "Latitude");


--
-- Name: idx_monitoringpost_created_at; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_monitoringpost_created_at ON public."MonitoringPost" USING btree ("CreatedAt");


--
-- Name: idx_monitoringpost_mobile; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_monitoringpost_mobile ON public."MonitoringPost" USING btree ("IsMobile");


--
-- Name: idx_monitoringpost_name; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_monitoringpost_name ON public."MonitoringPost" USING btree ("Name");


--
-- Name: idx_mueksdata_sensor_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_mueksdata_sensor_timestamp ON public."MUEKSData" USING btree ("SensorId", "DataTimestamp");


--
-- Name: idx_mueksdata_timestamp; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_mueksdata_timestamp ON public."MUEKSData" USING btree ("DataTimestamp");


--
-- Name: idx_mueksdata_visibility; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_mueksdata_visibility ON public."MUEKSData" USING btree ("VisibleRange");


--
-- Name: idx_sensor_active_type; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sensor_active_type ON public."Sensor" USING btree ("IsActive", "SensorTypeId");


--
-- Name: idx_sensor_error_created; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sensor_error_created ON public."SensorError" USING btree ("CreatedAt");


--
-- Name: idx_sensor_error_level; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sensor_error_level ON public."SensorError" USING btree ("ErrorLevel");


--
-- Name: idx_sensor_error_sensor; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sensor_error_sensor ON public."SensorError" USING btree ("SensorId");


--
-- Name: idx_sensor_last_activity; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sensor_last_activity ON public."Sensor" USING btree ("LastActivityUTC");


--
-- Name: idx_sensor_monitoringpost; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sensor_monitoringpost ON public."Sensor" USING btree ("MonitoringPostId");


--
-- Name: idx_sensor_results_checked; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sensor_results_checked ON public."SensorResults" USING btree ("CheckedAt");


--
-- Name: idx_sensor_results_sensor; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sensor_results_sensor ON public."SensorResults" USING btree ("SensorId");


--
-- Name: idx_sensor_results_success; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sensor_results_success ON public."SensorResults" USING btree ("IsSuccess");


--
-- Name: idx_sensor_serial; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_sensor_serial ON public."Sensor" USING btree ("SerialNumber");


--
-- Name: DOVData DOVData_SensorId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DOVData"
    ADD CONSTRAINT "DOVData_SensorId_fkey" FOREIGN KEY ("SensorId") REFERENCES public."Sensor"("Id") ON DELETE RESTRICT;


--
-- Name: DSPDData DSPDData_SensorId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DSPDData"
    ADD CONSTRAINT "DSPDData_SensorId_fkey" FOREIGN KEY ("SensorId") REFERENCES public."Sensor"("Id") ON DELETE RESTRICT;


--
-- Name: DustData DustData_SensorId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DustData"
    ADD CONSTRAINT "DustData_SensorId_fkey" FOREIGN KEY ("SensorId") REFERENCES public."Sensor"("Id") ON DELETE RESTRICT;


--
-- Name: AuditLogs FK_AuditLogs_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."AuditLogs"
    ADD CONSTRAINT "FK_AuditLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE SET NULL;


--
-- Name: Cameras FK_Cameras_MonitoringPost_MonitoringPostId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Cameras"
    ADD CONSTRAINT "FK_Cameras_MonitoringPost_MonitoringPostId" FOREIGN KEY ("MonitoringPostId") REFERENCES public."MonitoringPost"("Id");


--
-- Name: DOVData FK_DOVData_PollingSessions; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DOVData"
    ADD CONSTRAINT "FK_DOVData_PollingSessions" FOREIGN KEY ("PollingSessionId") REFERENCES public."PollingSessions"("Id");


--
-- Name: DSPDData FK_DSPDData_PollingSessions; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DSPDData"
    ADD CONSTRAINT "FK_DSPDData_PollingSessions" FOREIGN KEY ("PollingSessionId") REFERENCES public."PollingSessions"("Id");


--
-- Name: DustData FK_DustData_PollingSessions; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."DustData"
    ADD CONSTRAINT "FK_DustData_PollingSessions" FOREIGN KEY ("PollingSessionId") REFERENCES public."PollingSessions"("Id");


--
-- Name: IWSData FK_IWSData_PollingSessions; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."IWSData"
    ADD CONSTRAINT "FK_IWSData_PollingSessions" FOREIGN KEY ("PollingSessionId") REFERENCES public."PollingSessions"("Id");


--
-- Name: MUEKSData FK_MUEKSData_PollingSessions; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MUEKSData"
    ADD CONSTRAINT "FK_MUEKSData_PollingSessions" FOREIGN KEY ("PollingSessionId") REFERENCES public."PollingSessions"("Id");


--
-- Name: PollingSessions FK_PollingSessions_MonitoringPost; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PollingSessions"
    ADD CONSTRAINT "FK_PollingSessions_MonitoringPost" FOREIGN KEY ("MonitoringPostId") REFERENCES public."MonitoringPost"("Id") ON DELETE CASCADE;


--
-- Name: PuidData FK_PuidData_Puid; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PuidData"
    ADD CONSTRAINT "FK_PuidData_Puid" FOREIGN KEY ("PuidId") REFERENCES public."Puid"("Id") ON DELETE CASCADE;


--
-- Name: SensorResults FK_SensorResults_PollingSessions; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SensorResults"
    ADD CONSTRAINT "FK_SensorResults_PollingSessions" FOREIGN KEY ("PollingSessionId") REFERENCES public."PollingSessions"("Id");


--
-- Name: Snapshots FK_Snapshots_Cameras_CameraId; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Snapshots"
    ADD CONSTRAINT "FK_Snapshots_Cameras_CameraId" FOREIGN KEY ("CameraId") REFERENCES public."Cameras"("Id");


--
-- Name: IWSData IWSData_SensorId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."IWSData"
    ADD CONSTRAINT "IWSData_SensorId_fkey" FOREIGN KEY ("SensorId") REFERENCES public."Sensor"("Id") ON DELETE RESTRICT;


--
-- Name: MUEKSData MUEKSData_SensorId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."MUEKSData"
    ADD CONSTRAINT "MUEKSData_SensorId_fkey" FOREIGN KEY ("SensorId") REFERENCES public."Sensor"("Id") ON DELETE RESTRICT;


--
-- Name: PuidResults PuidResults_PuidId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."PuidResults"
    ADD CONSTRAINT "PuidResults_PuidId_fkey" FOREIGN KEY ("PuidId") REFERENCES public."Puid"("Id") ON DELETE CASCADE;


--
-- Name: Puid Puid_MonitoringPostId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Puid"
    ADD CONSTRAINT "Puid_MonitoringPostId_fkey" FOREIGN KEY ("MonitoringPostId") REFERENCES public."MonitoringPost"("Id") ON DELETE SET NULL;


--
-- Name: SensorError SensorError_SensorId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SensorError"
    ADD CONSTRAINT "SensorError_SensorId_fkey" FOREIGN KEY ("SensorId") REFERENCES public."Sensor"("Id") ON DELETE RESTRICT;


--
-- Name: SensorResults SensorResults_SensorId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."SensorResults"
    ADD CONSTRAINT "SensorResults_SensorId_fkey" FOREIGN KEY ("SensorId") REFERENCES public."Sensor"("Id") ON DELETE RESTRICT;


--
-- Name: Sensor Sensor_MonitoringPostId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sensor"
    ADD CONSTRAINT "Sensor_MonitoringPostId_fkey" FOREIGN KEY ("MonitoringPostId") REFERENCES public."MonitoringPost"("Id") ON DELETE SET NULL;


--
-- Name: Sensor Sensor_SensorTypeId_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Sensor"
    ADD CONSTRAINT "Sensor_SensorTypeId_fkey" FOREIGN KEY ("SensorTypeId") REFERENCES public."SensorType"("Id") ON DELETE RESTRICT;


-- 1. Заполнение типов датчиков
INSERT INTO public."SensorType" 
    ("SensorTypeName", "Description", "CreatedAt")
VALUES
    ('DSPD',  'Датчик состояния дорожного полотна', NOW()),
    ('IWS',   'IWS', NOW()),
    ('DOV',   'Датчик оптической видимости', NOW()),    
    ('DUST',  'Датчик концентрации пыли', NOW()),
    ('MUEKS', 'Модуль управления электроснабжением', NOW())
ON CONFLICT ("SensorTypeName") DO NOTHING;

-- 4. Стандартные конфигурации worker'ов
INSERT INTO public."WorkerConfiguration" 
    ("Key", "Value", "DataType", "Description", "IsActive")
VALUES 
    ('Polling.MaxConcurrentTasks', '100', 'integer', 'Максимальное количество параллельных задач опроса', true),
    ('Polling.TimeoutSeconds', '30', 'integer', 'Таймаут HTTP запросов в секундах', true),
    ('Polling.RetryCount', '3', 'integer', 'Количество повторных попыток при ошибке', true),
    ('Polling.RetryDelayMs', '1000', 'integer', 'Задержка между повторными попытками в мс', true),
    ('Logging.FileLogLevel', 'Information', 'string', 'Уровень логирования в файл', true),
    ('Logging.DatabaseLogLevel', 'Warning', 'string', 'Уровень логирования в базу данных', true),
    ('Configuration.RefreshIntervalSeconds', '60', 'integer', 'Интервал обновления конфигурации', true)
ON CONFLICT ("Key") DO NOTHING;


INSERT INTO public."Users"
("UserName", "PasswordHash", "Salt", "Role", "CreatedAt")
values
('user', 'knEX8Xp8Waa9/P89Qxy7DbEd5oumdgBA0/EVIh3XoFs=', 'FQjkR08swP471JN0g4F3UwG9zk61jjbTXx37rEHn17s=', 'User', CURRENT_TIMESTAMP),
('admin', '/WoSMsEmxNWymBFOfmcgNHAG/k0r2wGlNhDdEiHhKB8=', '5Wqvx4NTar97BqqKy7ozPSpV8Giys2GIt+fmIKYbAxI=', 'Admin', CURRENT_TIMESTAMP);