-- public."Users" definition

-- Drop table

-- DROP TABLE public."Users";

CREATE TABLE public."Users" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"UserName" varchar(100) NOT NULL,
	"PasswordHash" text NOT NULL,
	"Salt" text NOT NULL,
	"Role" varchar(50) NOT NULL,
	"CreatedAt" timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
	CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);
CREATE UNIQUE INDEX "IX_Users_UserName" ON public."Users" USING btree ("UserName");

INSERT INTO public."Users"
("UserName", "PasswordHash", "Salt", "Role", "CreatedAt")
values
('su', 'rwJ2gumZQW2BF5pz17tErROvQZW5kuALUC+PAVOA1bM=', 'ht3Dj16NdALjMXZeXVZH/Obouh83LI1u2SG19PQiVBY=', 'Admin', CURRENT_TIMESTAMP),
('user', 'knEX8Xp8Waa9/P89Qxy7DbEd5oumdgBA0/EVIh3XoFs=', 'FQjkR08swP471JN0g4F3UwG9zk61jjbTXx37rEHn17s=', 'User', CURRENT_TIMESTAMP),
('admin', '/WoSMsEmxNWymBFOfmcgNHAG/k0r2wGlNhDdEiHhKB8=', '5Wqvx4NTar97BqqKy7ozPSpV8Giys2GIt+fmIKYbAxI=', 'Admin', CURRENT_TIMESTAMP),
('and', 'uaF4nspGk0F+31E3Gftw4S3o/kohNdRXG8C60WPAB8o=', '9sKjH47MAHuAgNECD3sHA9hIDdfl+cW6E1NqtyoSdDM=', 'User', CURRENT_TIMESTAMP);

-- public."AuditLogs" definition

-- Drop table

-- DROP TABLE public."AuditLogs";

CREATE TABLE public."AuditLogs" (
	"Id" int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"Type" int4 NOT NULL,
	"Timestamp" timestamptz NOT NULL,
	"UserId" int4 NULL,
	"UserName" varchar(100) NULL,
	"Action" varchar(200) NULL,
	"Details" varchar(1000) NULL,
	"TargetId" int4 NULL,
	"HttpMethod" varchar(10) NULL,
	"Url" varchar(500) NULL,
	"IpAddress" varchar(50) NULL,
	"UserAgent" varchar(500) NULL,
	"IsSuccess" bool NULL,
	"ExecutionTimeMs" int8 NULL,
	"EntityType" varchar(200) NULL,
	"EntityId" int4 NULL,
	"ChangeType" varchar(50) NULL,
	"OriginalValues" jsonb NULL,
	"NewValues" jsonb NULL,
	"ChangedProperties" jsonb NULL,
	CONSTRAINT "PK_AuditLogs" PRIMARY KEY ("Id")
);
CREATE INDEX "IX_AuditLogs_Action" ON public."AuditLogs" USING btree ("Action");
CREATE INDEX "IX_AuditLogs_ChangeType" ON public."AuditLogs" USING btree ("ChangeType");
CREATE INDEX "IX_AuditLogs_EntityId" ON public."AuditLogs" USING btree ("EntityId");
CREATE INDEX "IX_AuditLogs_EntityType" ON public."AuditLogs" USING btree ("EntityType");
CREATE INDEX "IX_AuditLogs_Timestamp" ON public."AuditLogs" USING btree ("Timestamp");
CREATE INDEX "IX_AuditLogs_Type" ON public."AuditLogs" USING btree ("Type");
CREATE INDEX "IX_AuditLogs_UserId" ON public."AuditLogs" USING btree ("UserId");
CREATE INDEX "IX_AuditLogs_UserName" ON public."AuditLogs" USING btree ("UserName");


-- public."AuditLogs" foreign keys

ALTER TABLE public."AuditLogs" ADD CONSTRAINT "FK_AuditLogs_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE SET NULL;